axieinfinity/ronin

consensus/consortium/v2/consortium.go, params/config.go
The current consensus implementation call WrapUpEpoch before SubmitBlockReward which is the wrong order. We create a hardfork to make the contract call order correct.
=> Add Puffy hardfork

consensus/clique/clique.go, consensus/consensus.go, consensus/consortium/common/contract.go, consensus/consortium/main.go, consensus/consortium/v1/consortium.go, consensus/consortium/v2/consortium.go, consensus/ethash/consensus.go, core/blockchain.go, core/blockchain_reader.go, core/blockchain_test.go, core/chain_makers.go, core/evm.go, core/headerchain.go, core/state_processor.go, core/types.go, core/types/transaction.go, core/vm/evm.go, eth/api_backend.go, eth/state_accessor.go, internal/ethapi/backend.go, les/api_backend.go, light/lightchain.go
- Also returns system internal transactions from consortium
=> batch all internal transactions into 1 slices before sending to internalTxFeed

consensus/consortium/v2/snapshot.go
The len(snap.Validators) is not an invariant, it can be changed in the loop when a new list of validators is loaded. This commit removes that variable and uses len(snap.Validators)/2 + 1 instead.
=> fix: remove wrong validatorLimit local variable

cmd/ronin/main.go, cmd/ronin/usage.go, cmd/utils/flags.go, eth/api.go, miner/miner.go, miner/worker.go
Currently, when collecting transactions to commit to a block, we only check the accumulated gas with block's gas limit. Later, when finalizing the block, with system transactions included, the block's gas used may exceed the block's gas limit. As a result, that block is not mined. We want to avoid this scenario by introducing a new flag to reserve some gas in gas pool for system transactions.
=> Add reserved gas for system transactions

consensus/consortium/v2/consortium.go, consensus/consortium/v2/snapshot.go, params/config.go
This commit follows the approach of Ramanujan in BSC which includes the block
delay in block timestamp for verification on the recipients.
The block timestamp is calculated by the formula
- block timestamp = max(parent timestamp + block duration + backoff time,
current timestamp)
The block duration is 3s in the current configuration. When the validator is
inturn, the backoff time is 0, otherwise, each out of turn validator has a
different delay.
The delay equals to
- delay = wiggle + (random multiplier * wiggle/2)
The random multiplier is in range [1, len(current validators)]. The random seed
is the block number, the recipient can use the same seed to get the same random
result for verification.
=> feat: verify the block delay on broadcasted blocks

cmd/ronin/main.go, cmd/ronin/usage.go, cmd/utils/flags.go, eth/api.go, eth/ethconfig/config.go, miner/miner.go, miner/worker.go
This commit adapts BSC PR: https://github.com/bnb-chain/bsc/pull/112 to Ronin.
An empty block is pre-sealed by default. It's expected that a new block with
transactions is committed and abort the empty block producer if there are
pending transactions. However, with the low block time, in case there are a lot
of pending transactions, the commit transactions time exceeds the time an empty
block is produced. As a result, block with transactions is not produced but an
empty block and no real transactions is mined.
=> fix: avoid producing empty block when pending transactions is high

miner/worker.go
When FinalizeAndAssemble returns error, the caller functions does not check and log anything which causes difficulty when debugging. This commit adds a simple error log.
=> chore: add error log for FinalizeAndAssemble error

consensus/consortium/common/contract.go
Remove incorrect transaction hash and useless block hash information in submit block reward, wrap up epoch system transaction.
=> chore: clean up incorrect information in system transaction log

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/snapshot.go
Currently, when calculating the backoff time of not inturn validators, we
allocate different delay multipliers to each validator. As a result, the backoff
time ranges from [1, 11] seconds for not inturn validators given the wiggle time
is 1s and number of validators is 21. However, in that turn, some validators
cannot produce the block because they are in recently signed list. So we don't
need to allocate delay multipliers for those validators. Consequently, the
backoff time of not inturn validators shrinks to [1, 6] seconds, this helps to
reduce block time in case some validators are out of service.
=> feat: reduce backoff time of not inturn validators

core/block_validator.go, core/chain_makers.go, core/state_processor.go, core/types/block.go, core/types/bloom9.go, core/types/bloom9_test.go, core/types/transaction.go, eth/catalyst/api.go, miner/worker.go
- fix: correct the usage of AsyncReceiptBloomGenerator
AsyncReceiptBloomGenerator allows us the calculating bloom asynchronously with the caller, in this case the caller is applyTransaction. As a result, we don't need to CreateBloom in applyTransaction.
- feat: merge calculated blooms in receipts instead of recalculating
When all receipts have the calculated bloom filters, we can get the final bloom
filter by ORing them instead of looping through logs in receipts and
recalculating all things.
- test: add MergeBloom unit test and benchmark
=> fix: improve the bloom filter calculation

consensus/consortium/v2/consortium.go
Remove the condition that checks the transaction's gas price is 0 in system transaction check. This makes all transactions created by miners to core DPoS contracts system transactions and must go through verification on receiving nodes.
=> fix: prevent malicious miners from bypassing system transaction check

core/state_processor.go
As we will collect all logs from the receipts after finalizing the block, we must remove the log appending in each transaction to avoid duplication.
=> fix: duplicate logs returned by StateProcessor.Process

go.mod, go.sum, rpc/client.go, rpc/http.go, rpc/json.go
Previously, we change to use jsoniter for performance improvement. However, we get compatibility issue with the error handling, so we fallback to use json.
=> chore: fallback to use json instead of jsoniter

core/state/statedb.go, core/types/state_account.go
Get dirty accounts from `stateObjectsDirty` instead of `stateObjects`
=> fix: get dirty accounts from stateObjectsDirty instead of stateObjects

core/state/statedb.go, core/types/state_account.go
Change the DirtyAccount balance type from `string` to `*big.Int` to make it more transparent.
=> refactor: change dirty account balance from string to big.Int

core/blockchain.go, core/blockchain_reader.go, core/state/statedb.go, eth/api_backend.go, eth/tracers/api.go, internal/ethapi/backend.go, les/api_backend.go, light/lightchain.go
- Use BlockHash instead of ParentHash in DirtyAccount
- Convert []DirtyStateAccount to []*DirtyStateAccount
=> fix: use block hash instead of parent hash in dirty account

eth/tracers/api.go
This PR changed the API `debug_traceInternalsAndAccountsByBlockHash` response type from `internalTxs: Array<Object>` into `Map<TransactionHash, Object>` to add more information.
```json
{
"jsonrpc": "2.0",
"id": "1",
"result": {
"internalTxs": [
{
"result": {
"type": "CALL",
"from": "0x968d0cd7343f711216817e617d3f92a23dc91c07",
"to": "0xbddfb67348e0c8ef371d0d87e286d7d6ab918dd9",
"value": "0x0",
"gas": "0x53a0",
"gasUsed": "0x535c",
"input": "0x876e5861000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000359aef78ffa9807889258d0dd398172ca3b77eb100000000000000000000000045f60b415111e3e7abb4c79fc659d3dee430dff5",
"output": "0x", …
```
=> feat: update api debug_traceInternalsAndAccountsByBlockHash response type

core/types/block.go, core/vm/consortium_precompiled_contracts.go, core/vm/consortium_precompiled_contracts_test.go
We mistakenly calculate hash on the whole header which contains the signature. This lead to signature malleability issue as the another signature can be generated on the same block data without knowing the private key. And the check for same block data is bypassed due to calculating hash on 2 different signatures. This commit fixes the hash calculation to hash on header excluding the signature field.
=> fix: header's hash calculation in verifying double sign proof

consensus/consortium/v2/consortium.go
When trying get snapshot at forked block - 1, we call to contract to get state at that block which may not be available when chain head is ahead of that block. When that snapshot is calculated the first time (chain head is at that block, so the calculation always succeeds), we store that snapshot persistently to the disk. So, later query to that snapshot, we only need to load it from disk without re-calculating.
=> fix: try to load snapshot from disk at forked block before calculating

consensus/consortium/v2/consortium.go
We only restrict the system transaction check when buba hardfork happens.
=> fix: add hardfork logic to system transaction check

eth/tracers/api.go, eth/tracers/api_test.go
Get the current StateDB instead of using the parent StateDB since the old one is not updated so it will cause the StateRoot to be invalid.
- Fix invalid account root
- Fix concurrent task
- Fix balance response type
=> fix: invalid account root in traceAPI

eth/tracers/api.go
This PR adds `statedb.Finalise(vmenv.ChainConfig().IsEIP158(block.Number()))` after processing the transaction to finalize the state so any modifications are written to the trie.
=> fix(trace): finalise state in each tx

README.md
README is currently missing init genesis instruction. Missing genesis block would cause peering issues
=> fix: README misses init genesis instruction

.github/workflows/test-pr.yml
This commit uses github concurrency
(https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) to cancel CI running in previous commit of pull request, frees the queue for CI to run on newer commit.
=> ci: cancel runner jobs for previous commit of pull request

core/vm/instructions.go
This PR fixes the invalid input data of `Call` event since it is altered somewhere in the source code before publishing it into `SubscribeInternalTransaction` channel.
=> fix(instruction): invalid call input data

consensus/consortium/v1/consortium.go, consensus/consortium/v2/consortium.go
When profiling node sync with low number of transactions in block, we realize that initContract which unmarshalls JSON innerly consumes around 45% CPU. It is because we call initContract every time we want to call to contract which is redundant and this wastes a lot of CPU. We only need to call initContract when intializing the consensus engine and in Authorize function.
Before this commit:
+   44.92%     0.00%  ronin    ronin                [.] github.com/ethereum/go-ethereum/consensus/consortium/v2.(*Consortium).initContract
+   44.91%     0.00%  ronin    ronin                [.] github.com/ethereum/go-ethereum/consensus/consortium/common.NewContractIntegrator
+   44.79%     0.00%  ronin    ronin                [.] github.com/ethereum/go-ethereum/accounts/abi.JSON
After this commit:
+ …
=> fix: call initContract only when initializing consensus and Authorize

docker/chainnode/entrypoint.sh
It seems that password generation is broken for some time, but pr #77 makes it impossible to use any entrypoint args. `${1}` with current password generation implementation is the first entrypoint argument. At the same time we pass all entrypoint's arguments `"$@"` as extra arguments to ronin itself, thus we cannot use password length as an argument
=> fix: password generation inside docker entrypoint

consensus/consortium/main.go, consensus/consortium/v2/consortium.go, eth/state_accessor.go, eth/tracers/api.go, les/state_accessor.go
When getting over the DPoS hardfork, we get "insufficient funds for gas * price + value"
error when using debug API.
As the submitBlockReward is a system transaction, it's handled differently from
the normal transactions. When consensus processes submitBlockReward and there
are rewards from transaction fee in block, consensus transfers balance from
SystemAddress to miner address through the statedb.SetBalance directly. Later,
when the system transaction is created, this reward will be transfer from miner
to staking contract.
Currently, in debug API and state accessor, we treat all transactions as normal
transactions.  Without special handling, we miss the state transaction to
transfer balance from SystemAddress to miner. Consequently, when the system
transaction is processed, we get the …
=> fix: handle submitBlockReward correctly when processing system transanctions

.github/workflows/release-master.yml, .github/workflows/release-nightly.yml
We need to setup the other public pipeline for main branch which supports for development phase.
=> ci: setup public pipline for master branch with nightly tag

eth/handler.go
This failure happens when a peer connects with snap protocol but does not support eth protocol. This is not so critical so we reduce the log level from error to info.
=> chore: reduce log level of snapshot registration failure

consensus/consortium/main.go
We mistakenly use SetBalance instead of AddBalance to update the balance of miner when transfer the token from SystemAddress to miner. This commit corrects the balance update.
=> fix: wrong balance update in HandleSubmitBlockReward

consensus/consortium/main.go, consensus/consortium/v2/consortium.go, eth/backend.go, miner/worker.go
We have an issue that a miner A is inturn for block 10. At block 9, due to a
node is down, miner A mines the out of turn block 9 and broadcast to the
network. As a result, miner A cannot mine block 10 due to recently signed rule.
However, at block 9, there is another miner B that mines block 9' and this block
is accepted by most of nodes in the network. Then based on block 9', block 10 is
mined by miner C and there is a slash transaction for miner A because on network
view block 9 is mined by miner B not miner A. Miner A receives the chain 9' -
10 and reorgs to that chain. In theory, miner can mine the block 10' which
creates a canonical has greater difficulty. This drops the block 10 and the
slash transaction. However, currently, miner tries to mine block 11 instead of
reproducing new …
=> fix: miner does not mine its inturn block

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/snapshot.go, params/config.go
This commit takes inspiration from section 5.3 BEP-172: Network Stability Enhancement On Slash Occur (https://github.com/bnb-chain/BEPs/pull/172)
When a validator is down, its block turn is mined by an out of turn miner. So when comes the turn of out of turn miner, it may not be able to produce block due to it is already in recently signed list. This leads to a series of out of turn blocks which increase the overall block time because currently out of turn block takes a least 4s. This commit allows out of turn block to take only 3s if the inturn validator is already in recently signed list.
=> feat: reduce block time of out of turn miner

consensus/consortium/v2/consortium.go, consensus/consortium/v2/snapshot.go
The first validator in snap.Recents is shifted out and allowed to seal the block already. However, when determining if we should slash the validator we mark that first validator as unable to seal block which is incorrect. This loosens the slash check rule. This commit fix this bug and create a separate helper function to check if the validator recently signed a block.
=> fix: recently signed check when slashing unavailable validator

cmd/ronin/accountcmd.go, docker/chainnode/entrypoint.sh
- fix: don't create account automatically
Currently, we automatically create account when no private key is provided and
there is not account in keystore. This behavior may lead to mistakes when
setting up node, so we remove this behavior in this commit.
- fix: abort if the private key is different from existed account
This commit creates a subcommand check in account command of Ronin to check if
the corresponding account of provided private key exist in the imported account.
When starting Ronin from entrypoint.sh, if the provided private key is different
from imported account, the process is aborted.
=> fix: abort if the private key is different from existed account

core/tx_pool.go, trie/iterator.go, trie/iterator_test.go
- core: fix the order of address in queue
reverse the order of address in queue
- trie: fix two issues in trie iterator
+ trie: fix memory leak in trie iterator
In the trie iterator, live nodes are tracked in a stack while iterating.
Popped node states should be explictly set to nil in order to get
garbage-collected.
+ trie: fix empty trie iterator
=> fix: cherry pick bug fixes from go-ethereum

miner/worker.go
Strictly speaking, this logic can apply after some blocks passing the Consortium v2 hardfork so that when going backward the chain we are still on Consortium v2. This helps to avoid division by 0 error because of not being able to get validator list when not passing the Consortium v2. We intend to release this logic together with Olek hardfork so just check with Olek hardfork here for symplification.
=> fix: apply GetBestParentBlock only after Olek hardfork

genesis/testnet.json, params/version.go
The planned hardfork block is 16,849,000 around Tue, 16 May 2023, 6:00 GMT (https://saigon-app.roninchain.com/block/16849000)
=> config: add Olek hardfork on testnet

.github/workflows/release-nightly.yml, .github/workflows/release.yml
Currently, the only submodule in Ronin is tests/testdata, this submodule is not necessary for building image. This commit removes submodule fetch when checkout repository for building image to reduce the build time.
=> ci: checkout repository without submodule when building image

core/vm/consortium_precompiled_contracts.go, core/vm/consortium_precompiled_contracts_test.go
Golang from v1.18 has more powerful sort algorithm call pdqsort instead of quicksort. Therefore, I change the current implement (quicksort) to built-in sort which is using pdqsort
=> chore: optimize sortValidators using pdqsort in golang

core/vm/instructions.go
DELEGATECALL event always publishes the message with a value equal to 0 to the channel.
Get the value from the parent contract instead of hardcode 0 to the message.
=> fix(vm): update DELEGATECALL event with correct value parameter

core/blockchain_reader.go, core/types/transaction.go
We remove the logic to create a internal transaction message with type transfer because this message type is not useful anymore. When checking for the change of token balance, we should rely on the opcode field not the message type.
=> chore: remove transfer type in internal transaction logic

core/vm/evm.go, core/vm/interpreter.go, eth/tracers/api.go
Sometimes we want to capture the error from the tracer. However, the default tracer does not support these errors such as `max call depth exceeded` and `insufficient balance for transfer` in internal transactions.
Currently, the default tracer in Ronin does not provide support for capturing certain errors that occur during internal transactions, such as `max call depth exceeded` and `insufficient balance for transfer`.
This PR aims to address this issue by introducing a new parameter, `emitTraceError: bool`, to the trace API. This addition ensures compatibility with the existing API while enabling the capture of these errors.
```bash
curl --location 'localhost:8545' \
--header 'Content-Type: application/json' \
--data '{
"jsonrpc": "2.0",
"method": …
```
=> feat/tracers: support emit trace error

crypto/bls/signature_batch_test.go
We randomly observe this failure when running unit test
go test -test.v -run=^TestSignatureBatch_AggregateBatch/common_and_uncommon_messages_in_batch_with_multiple_messages
=== RUN   TestSignatureBatch_AggregateBatch
=== RUN   TestSignatureBatch_AggregateBatch/common_and_uncommon_messages_in_batch_with_multiple_messages
signature_batch_test.go:643: AggregateBatch() Descriptions got = [test signature bls aggregated signature test signature bls aggregated signature test signature bls aggregated signature], want [bls aggregated signature test signature bls aggregated signature test signature bls aggregated signature test signature]
--- FAIL: TestSignatureBatch_AggregateBatch (0.02s)
--- FAIL: TestSignatureBatch_AggregateBatch/common_and_uncommon_messages_in_batch_with_multiple_messages …
=> crypto/bls: fix bls signature batch unit test

core/vote/vote_manager.go, core/vote/vote_pool.go, core/vote/vote_pool_test.go, eth/backend.go
This commit limits the number of votes in future queue per peer as the vote in future queue is not fully verified. The check happens before the costly basicVerify which has to verify the BLS signature.
=> core/vote/vote_pool: protect pool against malicious peer

Makefile
We randomly get error in CI
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
As in blst documentation, we need to provide CGO_CFLAGS="-O -D__BLST_PORTABLE__" to make the compiled blst portable across different CPU. This commit adds this CGO_CFLAGS to the build process.
=> build: add cflags to build portable blst library

cmd/faucet/faucet.go, cmd/ronin/config.go, cmd/utils/flags.go, ethstats/ethstats.go
In order to serve new feature of ronin-stats (knowing coinbase of connected node), I've added coinbase which is get from eth.Etherbase() function.
Empty coinbase is still allowed in case nodes run without adding any account into account manager
=> ethstats: add coinbase to nodeInfo

consensus/consensus.go, consensus/consortium/common/constants.go, consensus/consortium/common/contract.go, consensus/consortium/common/types.go, consensus/consortium/main.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/finality/consortium_header.go, consensus/consortium/v2/snapshot.go, params/config.go
This commit extends the snapshot to contains additional BLS public key of the
validators. The new information is also added to header's extra data like
aggregated BLS signature and voted validator information. A new system
transaction is created to reward the finality voted validators.
=> consortium/v2: add finality vote to consensus layer

cmd/ronin/main.go, cmd/ronin/usage.go, cmd/utils/flags.go, eth/backend.go, eth/ethconfig/config.go, eth/handler.go, eth/handler_ronin.go, eth/handler_ronin_test.go, eth/peer.go, eth/peerset.go, eth/protocols/eth/peer.go, eth/protocols/eth/peer_test.go, eth/protocols/known_cache.go, eth/protocols/ronin/handler.go, eth/protocols/ronin/peer.go, eth/protocols/ronin/protocol.go, p2p/peer.go
ronin protocol is an extension protocol of eth, a peer is required to support eth protocol to run ronin protocol. ronin protocol currently only supports NewVotePacket which contains a list of finality votes.
=> eth/protocols: implement finality vote communication via ronin protocol

core/vote/vote_pool.go
The FetchVoteByBlockHash is called by the consensus engine and we don't want this function to block the consensus engine's operations. Currently, FetchVoteByBlockHash uses RLock to wait to acquire the read lock but as the writers are uncontrolled, it can be blocked when there are a lot of spamming writers. This commit makes FetchVoteByBlockHash to use TryRLock to keep polling for the lock n times and returns nil in case it cannot acquire the lock. This helps to bound the max duration a caller must wait on this function.
=> vote/vote_pool: use TryRLock in FetchVoteByBlockHash

core/vm/consortium_precompiled_contracts.go, core/vm/consortium_precompiled_contracts_test.go, core/vm/contracts_test.go, params/protocol_params.go
This precompiled contract is called by system contract to verify signature from the provided proof of finality vote violation. It checkes if there is a validator has contributed to 2 aggregated signatures on the 2 distinct block with the same height.
=> core/vm: add precompiled contract to verify finality vote violation proof

Makefile
Currently, we only add CGO flags when running 'make ronin', so sometimes we still get the error related to blst library built without the CGO_CFLAGS. This commit adds the CGO flags to all places when we use 'go run' to build the binary.
=> build: add CGO flags to all build targets

consensus/consortium/common/contract.go, consensus/consortium/generated_contracts/profile/profile.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, params/config.go
This commit adds the contract interaction to get BLS public when preparing checkpoint block. This also creates a getCheckpointValidatorsFromContract function to be used in both Prepare and Finalize the checkpoint block. Besides, a new interface ContractInteraction is created for mock test contract interaction.
=> consortium/v2: add contract interaction to get BLS public key

eth/backend.go
When the vote pool is enabled, make the consortium consensus engine use it.
=> eth/backend: add vote pool to consortium engine

core/blockchain.go
In fork choice, we only need to compare the difficulty of forks when the justified block numbers are the same in those forks. Otherwise, we choose the fork with higher justified block number. This commit fixes a bug in current fork choice to make it follow the correct behavior.
=> blockchain: check total difficulty only when having same justified block number

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go
Due to the change in REP-0003, a block is finalized when there are at least floor(2/3*numValidators) + 1, this commit changes the calculation to follow the rule.
=> consortium/v2: edit the finality vote threshold

consensus/consortium/v2/api.go, consensus/consortium/v2/consortium.go
This commit adds 2 APIs in consortiumv2 namespace:
consortiumv2_getValidatorAtHash, consortiumv2_getFinalityVoteAtHash.
consortiumv2_getValidatorAtHash returns the authorized validators that can seal
block hash with BLS public key. consortiumv2_getFinalityVoteAtHash returns the
finality vote information in the block header at block hash.
=> consortium/v2: add RPC API for querying finality vote easily

consensus/consortium/main.go, consensus/consortium/v2/consortium.go
- consortium: add VerifyVote to the outer consortium
As required by the FastFinalityPoSA interface, VerifyVote is needed in the outer
consortium. We add VerifyVote to outer consortium which simply forwards to the
consortium v2 function.
- consortium/v2: access blsPublicKey only after Shillin
The BLS public key is only available in checkpoint header after Shillin, so
don't access this field before Shillin.
=> consortium/v2: add VerifyVote and fix blsPublicKey access

consensus/consortium/v2/consortium.go
Currently, to check if the justified block number - 1 is justfied, we look at the snapshot at justfied block number - 1. This is incorrect because at the snapshot N, the maximum justified block number is N - 1. So, we need to look at the snapshot at justified block number to check if the justified block number - 1 is justified.
=> consortium/v2: fix the incorrect snapshot lookup in GetFinalizedBlock

core/vote/vote_pool.go, core/vote/vote_pool_test.go
The vote which targets the block number that is older or equal to justified block number is not useful anymore. We can reject and prune those votes from pool.
=> vote/vote_pool: reject older than justified block number vote

consensus/consortium/v2/consortium.go
The contract field in consortium v2 consensus engine is written under the call to Authorize. The Authorize function is called only once in startup and can run concurrently with other funtions that read the contract field which leads to data race. We move this write under the mutex lock and the read of this field into readSignerAndContract function to avoid data race.
=> consortium/v2: protect the contract interaction under mutex

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/finality/consortium_header.go, core/vote/vote_pool_test.go
Currently, a vote with wrong target number is not assembled into block as there
is a check in assembleFinalityVote. In this commit, we move that check to
VerifyVote to reject the vote earlier in vote pool, avoid the vote pool to be
DOSed.
=> consortium/v2: reject the vote with wrong target number

core/state/trie_prefetcher.go
We randomly observed RPC handler crash as below
```
Trie prefetcher failed opening trie      root=fa2e9d..feb309 err="missing trie node fa2e9d5691bc60f8fd9954a3b5d7cee13b5e6cd62ce89300dda9f6b60efeb309 (path )"
RPC method eth_getCode crashed: unknown trie type <nil>
goroutine 262465 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
github.com/ethereum/go-ethereum/rpc/service.go:200 +0x9e
panic({0x1e77de0, 0xc04b6d4b20})
runtime/panic.go:890 +0x263
github.com/ethereum/go-ethereum/core/state.(*cachingDB).CopyTrie(0x1e9a560?, {0x0?, 0x0?})
github.com/ethereum/go-ethereum/core/state/database.go:158 +0x145
github.com/ethereum/go-ethereum/core/state.(*triePrefetcher).copy(0xc04a9cd040)
github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:130 +0x930 …
```
=> core/state: filter out nil trie for copy (#25575)

eth/handler.go, eth/handler_eth.go, eth/sync.go
Fixes an issue where waitgroups were used erroneously, which could lead to waitgroup being added to while wait was already invoked.
We randomly observed this when restart node running with race detector
```
Read at 0x00c005eef778 by goroutine 37506:
runtime.raceread()
<autogenerated>:1 +0x24
github.com/ethereum/go-ethereum/eth.(*handler).runSnapExtension()
github.com/ethereum/go-ethereum/eth/handler.go:366 +0x79
github.com/ethereum/go-ethereum/eth.(*snapHandler).RunPeer()
github.com/ethereum/go-ethereum/eth/handler_snap.go:33 +0x44
github.com/ethereum/go-ethereum/eth/protocols/snap.MakeProtocols.func2()
github.com/ethereum/go-ethereum/eth/protocols/snap/handler.go:102 +0xee
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1() …
```
=> eth: better active protocol handler tracking (#27665)

go.mod, go.sum
blst v0.3.11 fixes this vulnerability. This vulnerability does not affect us because the wrapper we use does not call SigValidate with sigInfcheck argument set to true. However, it is not bad to bump to the latest version.
=> go.mod: bump blst to v0.3.11

cmd/devp2p/dnscmd.go, cmd/devp2p/nodesetcmd.go, params/config.go, script/gen_dns_txt.sh
- devp2p: add IP filter and ronin mainnet/testnet filter for nodeset filter
This commit adds IP or-filter, updates the ronin mainnet and testnet
configuration that are used for nodeset filter. This also allows DNS sign to use
password file instead of entering via prompt.
- script: add script to generate DNS TXT record from list of nodes
=> devp2p: add IP filter and ronin mainnet/testnet filter for nodeset filter

Makefile, build/ci.go
With this commit, we can use `make ronin-race-detector` to build ronin with race detector.
=> build: add option to build ronin with race detector

consensus/consortium/common/contract.go, consensus/consortium/generated_contracts/finality_tracking/finality_tracking.go, consensus/consortium/v2/consortium.go, params/config.go
Because the finality votes are assembled after we FinalizeAndAssemble the block and the finality reward distribution transaction is in FinalizeAndAssemble, we cannot reward the finality voters in the current block right away. Instead, the reward distribution is delayed until next block. So in the FinalizeAndAssemble, we look at the finality voters in the parent header and distribute reward to them.
=> consortium/v2: distribute finality reward for the voters in parent block

genesis/testnet.json, params/config.go
This commit adds a Shillin hardfork on testnet to enable optimistic fast finality. The hardfork is scheduled around Sept 12 2023, 7:00 GMT+7 (https://saigon-app.roninchain.com/block/20268000)
=> params: add optimistic fast finality testnet configuration

monitor/finality_vote.go, monitor/finality_vote_test.go, monitor/slack_alerter.go
The slack webhook URL for alerting is input via the environment variable SLACK_WEBHOOK_URL.
=> monitor/finality: add slack alert for fast finality rule violation

cmd/ronin/main.go, cmd/ronin/usage.go, cmd/utils/flags.go, core/blockchain.go, core/events.go, eth/backend.go, eth/ethconfig/config.go, miner/worker.go
This commit adds the finalized block number and block hash to chain event in writeBlockWithState. It also adds the additionalchainevent.enable flag and moves all blockchain's functionality related to subscriber under this flag.
=> blockchain: add the finalized block number and block hash to chain event

eth/api_backend.go
This commit adds nil check for finalized block before getting the header in HeaderByNumber.
=> eth/api_backend: check nil finalized block in HeaderByNumber

core/state_processor.go
We need to update the check in applyTransaction to support the whitelist deployer version 2. However, since we move the whitelist deployer check to the later Create operation to cover both CREATE2/CREATE opcode and contract deploy transaction, this check is not necessary anymore.
Does removing this check create backward incompatibility (cannot sync from genesis)?
The backward incompatability happens only when the old transactions does not pass the check and when running with newer Ronin version, it passes because we remove the check. However, this is not the case here, as the error in applyTransaction means the transaction is not included into the block.
=> state_processor: remove the whitelist deployer check in applyTransaction

cmd/utils/flags.go, core/tx_pool.go, eth/api.go, miner/miner.go, miner/worker.go, params/protocol_params.go
This commit adds the reserved gas for system transaction, which is previously a
user provided flag, as a constant.
In the miner part, the miner stops commit normal transactions to block when
block gas used is over the block's gas limit - reserved gas. So when finalizing
and including system transactions into block, the block's gas used does not exceed
the block's gas limit.
In the txpool part, when validating a transaction before putting it into the
pool, previously, we only check if the transaction's gas limit is not over the
block's gas limit. However, if the transaction's gas limit is over the block's
gas limit - reserved gas, it is never included into the block but still always
stay in pending transaction pool. This commit fixes the check to reject the
transaction with gas limit over …
=> miner, txpool: add a reserved gas constant for system transactions

genesis/mainnet.json, p2p/peer.go, params/version.go
Estimated hardfork time 14:00 UTC+7 Oct 26 (https://app.roninchain.com/block/28825400)
=> chainconfig: add Shillin and Antenna hardfork on mainnet

.github/workflows/release.yml
Currently, when publishing a new release using Github UI, we trigger 3 release workflows. It looks like that 3 action types: created, published, released trigger the workflow. This commit restricts the release workflow to run on published activity type only.
Reference:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
- https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=published#release
=> github/workflows: fix the release workflow

cmd/utils/flags.go
Fix the incorrect config set when --monitor.finalityvote is used.
=> cmd/flag: correctly enable finality vote monitor

core/blockchain.go, core/events.go, eth/filters/api.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go
* Allow users to subscribe to constantly receive notifications about latest finalized blocks
=> eth/filters: add finalized block subscription

cmd/ronin/config.go, cmd/ronin/main.go, cmd/ronin/usage.go, cmd/utils/flags.go, consensus/consortium/common/mock_contract.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/snapshot.go, eth/ethconfig/config.go
In order to setup and test Ronin nodes locally, we need to do the following steps:
- Config and deploy DPOS contracts on consortium v1
- Add DPOS contracts to genesis file and define forked block number to switch to consortium v2
These steps could affect to demands of developing and testing other features.
Therefore, the ideas of running consortium v2 node without DPOS contracts are come up. 
- In order to do that, we need to implement a mock layer for `ContractInteraction` to mock all of the following function (mock_contract):
```
GetValidators(blockNumber *big.Int) ([]common.Address, error)
WrapUpEpoch(opts *ApplyTransactOpts) error
SubmitBlockReward(opts *ApplyTransactOpts) error
Slash(opts *ApplyTransactOpts, spoiledValidator common.Address) error
FinalityReward(opts …
```
=> consortium: Implement mocking logics for consortium v2

core/blockchain_test.go, core/state_transition.go, core/tx_list.go, core/tx_pool.go, core/tx_pool_test.go, internal/ethapi/api.go
- tx_pool, state_transition: accept sponsored tx with expired time = 0
The sponsored transaction with expired time = 0 means there is no expired time
for that transaction, so we skip the expired time check for that one.
- api: add payer field to sponsored transaction in RPC response
This commit adds payer field to sponsored transaction in RPC response of APIs
related to transactions to easy lookup without manually recovering from the
returned payer's signature.
- txpool: update the signer of txlist when it differs from txpool's signer
txpool's signer can change when we reach higher block that triggers the new
signer. This commit checks the txpool's and txlist's signer when adding the new
transaction to txlist, update the txlist's signer with txpool's one when they
differ.
- …
=> tx_pool, state_transition: accept sponsored tx with expired time = 0

core/state/snapshot/difflayer.go, core/state/snapshot/snapshot_test.go
This fixes the flaky unit test TestDiffLayerExternalInvalidationPartialFlatten we sometimes observe. The expected behavior is that we get the error when query account or storage slot from stale diff layer. However, the staleness check is done after the bloom filter check. If we get the bloom filter miss in diff layer, we go directly to disk layer, so we don't go through the staleness check in diff layer. The test is flaky because bloom filter is randomized. This commit moves the staleness check earlier before bloom filter check.
More details at: https://github.com/ethereum/go-ethereum/issues/27254
=> core/state/snapshot: check difflayer staleness early (#27255)

metrics/counter.go, metrics/ewma.go, metrics/gauge.go, metrics/meter.go
We observe the data race warning when enabling metric
```
Read at 0x00c02cc7fe90 by goroutine 49:
github.com/ethereum/go-ethereum/metrics.(*StandardMeter).Snapshot()
github.com/ethereum/go-ethereum/metrics/meter.go:244 +0x6e
github.com/ethereum/go-ethereum/metrics/prometheus.Handler.func1()
github.com/ethereum/go-ethereum/metrics/prometheus/prometheus.go:55 +0x3c2
Previous write at 0x00c02cc7fe90 by goroutine 251:
sync/atomic.AddInt64()
runtime/race_amd64.s:289 +0xb
sync/atomic.AddInt64()
<autogenerated>:1 +0x1b
github.com/ethereum/go-ethereum/p2p.(*rlpxTransport).WriteMsg()
github.com/ethereum/go-ethereum/p2p/transport.go:103 +0x4c3
github.com/ethereum/go-ethereum/p2p.(*conn).WriteMsg()
<autogenerated>:1 +0xb9
```
The data race happens on StandardMeter.snapshot.temp …
=> metrics: use atomic type (#27121)

docker/chainnode/entrypoint.sh
Current code does not re-calculate accountsCount after importing private key. As a result, the unlock account logic is not triggered. This commit moves the unlock logic earlier right after we import the key.
=> entrypoint: move the unlock account logic to right after importing key

.github/workflows/test-pr.yml, Makefile
Using flag coverage in ci.go for enabling atomic cover_mode. 
=> ci: add test coverage

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, core/blockchain.go, core/chain_makers.go, core/state_processor_test.go
If the chain is reorganized because the newly submit block has higher justified block number, it can be reverted back to the old chain prior to reorg because the old blocks cause `ErrKnownBlock` during insertion via the `insertChain` method, which invokes `writeKnownBlock` to set the old chain as the canonical chain again.
=> blockchain: fix inconsistent reorg behavior

consensus/consortium/v2/consortium.go
The `verifyFinalitySignatures` function is invoked in `VerifyHeaderAndParents` before the condition
`parent.Number.Uint64() == number-1 && parent.Hash() == header.ParentHash` is checked. This can result in generating and storing an invalid snapshot because the block number and block hash provided as inputs for `snapshot` do not match. If the `if number == c.forkedBlock-1` block is executed, this can lead to overwriting past snapshot with invalid data.
=> consortium: fix not validated snapshot query

cmd/ronin/main.go, cmd/ronin/usage.go, cmd/utils/flags.go
* eth, cmd: allow FdLimit to be set in config/command line (#24148)
* eth/ethconfig: format code
* cmd, eth/ethconfig: simplify fdlimit arg, disallow toml
* cnd/utils: make fdlimit setting nicer on the logs
-----
Currently, we set the OpenFilesCacheCapacity leveldb's option to system fd limit / 2
```
// OpenFilesCacheCapacity defines the capacity of the open files caching.
OpenFilesCacheCapacity int
```
This can be the reason for high memory in page cache (high active_file in /sys/fs/cgroup/memory/memory.stat). We cherry-pick this commit to allow setting fdlimit through CLI to reduce the cache capacity in leveldb.
=> cmd: allow file descriptor limit to be set via CLI (#24477)

cmd/ronin/main.go, cmd/ronin/usage.go, cmd/utils/flags.go, core/blockchain.go, core/blockchain_test.go, eth/backend.go, eth/ethconfig/config.go, les/handler_test.go, les/peer.go, les/server_requests.go, les/test_helper.go
This commit adds --triesinmemory flag to configure the number of tries that is kept in memory before pruning.
=> blockchain: make tries in memory configurable via flag

consensus/consortium/common/contract.go, core/state_transition.go, eth/api_backend.go, eth/gasestimator/gasestimator.go, eth/tracers/api.go, ethclient/gethclient/gethclient.go, ethclient/gethclient/gethclient_test.go, go.mod, go.sum, graphql/graphql.go, graphql/graphql_test.go, internal/ethapi/api.go, internal/ethapi/api_test.go, internal/ethapi/backend.go, internal/ethapi/transaction_args.go, internal/web3ext/web3ext.go, les/api_backend.go
Some notable changes:
- EstimateGas on latest block instead of pending block when block argument is not provided
- Add support for block overrides in eth_call
- Add support for state overrides in eth_estimateGas
- Reduce the binary search iterations in EstimateGas
+ Return 21000 for plain transfer when simulated successfully
+ Favor lower bound in binary search
+ Don't try to perfect gas estimation, return early when the lower-higher range is smaller than error ratio
+ Run the second iteration with `gas = (result.UsedGas + result.RefundedGas + params.CallStipend) * 64 / 63` to reduce the binary search range
=> internal/ethapi: cherry pick EstimateGas improvement from go-ethereum

consensus/consortium/common/contract.go, consensus/consortium/common/contract_test.go
- consortium-v2: check that sender of system transaction is EOA
Following EIP-3607 ("Reject transactions from senders with deployed code"), if
the sender of transaction has deployed code (not an EOA), the transaction is
rejected. This commit adds the same check to system transaction.
- consortium-v2: cleanup the check of system transaction's sender with coinbase
Currently, the system transaction's sender check looks weird, it still allows
that sender is different from coinbase. However, the sender is checked to be
equal to coinbase in IsSystemMessage already, so there must be no issue here.
This commit fixes that check in ApplyTransaction, we keep this check to make it
more explicit though the check is redundant.
=> consortium-v2: fix the system transaction's sender check in ApplyTransaction

core/tx_pool.go, miner/worker.go, params/protocol_params.go
Currently, reserved gas for system transaction is hardcoded as 10M gas. (https://github.com/axieinfinity/ronin/blob/95e3707865263a9c751307c951ef5c02a8247717/miner/worker.go#L879-L890). However, only the checkpoint block - 1 (the block at the end of epoch) needs to reserve that much (because wrap up epoch transaction requires a lot of gas), it is necessary to adjust the logic to reserve lower gas in normal block or higher gas in checkpoint block.
=> core: adjust reserved gas for system transactions in non-checkpoint block

consensus/consortium/v2/api.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/finality/consortium_header.go, consensus/consortium/v2/snapshot.go, crypto/bls/blst/public_key.go, monitor/finality_vote.go
Currently, HeaderExtraData is encoded/decoded manually, which is error prone and hard to extend. Hence, this PR implements a new RLP encoder/decoder for HeaderExtraData and changes to use this new method.
=> consortium-v2: new RLP encoder/decoder for HeaderExtraData

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, core/vm/consortium_precompiled_contracts.go, core/vm/consortium_precompiled_contracts_test.go, core/vm/contracts_test.go, core/vm/evm.go, params/config.go
- precompiled: add contract for sorting validator with random beacon
This new precompiled contract provides requestSortValidatorSet and
pickValidatorSet function. The requestSortValidatorSet receives the list of all
validator candidates, pick non-rotating validators based on staked amounts and
rotating validators based on weight derived from random beacon. The list of
validators for all epoch of that period is stored in precompiled contract's
storage. The pickValidatorSet supports query the validator set of an epoch in
that period.
- consortium-v2: enable pick validator with beacon at Tripp hardfork - 1
Since precompiled contract has no code, it can be marked as empty account if
nonce and balance is 0 too. If the account is empty, the account node is deleted
so writing to storage of that …
=> consortium-v2, precompiled: add contract for sorting validator with random beacon

consensus/consortium/v1/snapshot.go, consensus/consortium/v2/snapshot.go, core/rawdb/database.go, core/rawdb/schema.go
This commit adds the key that Consortium snapshot uses to store the value into key-value DB to database inspect command. This helps to get storage stats of Consortium snapshot.
=> rawdb: add Consortium snapshot to inspect db's result

core/blockchain.go
Before commit bf2f0d1787d ("blockchain: fix inconsistent reorg behavior"), the write known block only checks the if the external total difficulty (TD) is higher than local one without following the fast finality rule, so it can reorg an justified block. That commit replaces the check with reorgNeeded function to enforce the fast finality rule. However, the reorgNeeded function does not strictly enforce that the external TD is higher than local one, it allows that the external TD may be equal to the local one. This leads to warning with an impossible reorg case.
This commit adds back the TD check combining with the reorgNeeded function to correcly enforce the rule here.
Fixes: #403
=> blockchain: fix the write known block check

docker/chainnode/entrypoint.sh
The miner.gastarget is deprecated and has no effect now. This commit removes this flag from the entrypoint.sh.
=> entrypoint: remove deprecated unused miner.gastarget

p2p/server.go
Currently, DNS resolved candidates of eth protocol are added as candidates for dialing but not added to DHT. The DHT's seed nodes are still configured via hardcoded nodes in bootnodes flag. As we want to replace the hardcoded bootnodes entirely with DNS resolved nodes, we resolve some nodes from the DNS discovery URL and put them into DHT when setting up the p2p discovery.
=> p2p/server: add DNS resolved candidates to distributed hash table

core/vm/operations_acl.go
This partially cherry-picks the commit https://github.com/ethereum/go-ethereum/commit/ac0ff044606a663eeb47ef60ed5506f842753084 to add the overflow check when doing gas calculation in EIP 2929.
=> core/vm: fix overflow in EIP 2929 gas calculation

cmd/utils/flags.go, mobile/params.go, params/bootnodes.go
Replace the default Ethereum foundation mainnet bootnodes by Ronin bootnodes for avoiding unused discovery and peering in Network.  We have 2 options for extending the bootnodes now 
1. Overwrite by setting Bootnodes ENV
2. We automatically fetch 5 endpoints from DNS discovery, implemented in https://github.com/axieinfinity/ronin/pull/370
=> params/bootnodes: remove default etherum mainnnet bootnodes

consensus/consortium/common/contract.go
Currently, in system transaction we increase nonce after transaction execution
which is not consistent with normal transaction. This change does not require a
hardfork as:
- Nonce is not used when executing transaction in virtual machine
- Consortium-v2 is after Byzantium so we don't fall through the path to
calculate root hash after transaction execution
Reference: https://github.com/bnb-chain/bsc/pull/2185
=> consortium-v2: increase the nonce of sender before transaction execution

consensus/consortium/common/contract.go, consensus/consortium/common/mock_contract.go, consensus/consortium/v1/consortium.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/finality/consortium_header.go
* To tackle reorg-based attack, this PR changes contract query to using block hash.
* Minor fix: newLimit would be updated with new rule after Tripp effective
=> consortium-v2: query contract based on block hash

cmd/ronin/accountcmd.go
loadBlsSecretKey is called in `account generate-bls-proof` to support loading BLS secret key from file. But this command also supports loading secret key from keystore. In that case, no keyfile is given and this function should return error so the command can handle the error and switch to load secret key from keystore instead of exit.
=> accountcmd: return error instead of exit in loadBlsSecretKey

consensus/consortium/v2/snapshot.go
After Tripp is effective, the checkpoint validators in header's extra data is set only at the period block, not at all checkpoint blocks anymore. So only update snapshot's validator with bls public key when checkpoint validator is not empty.
=> consortium-v2: only update snapshot's voter when it is not empty in header

consensus/consortium/v2/finality/consortium_header.go, consensus/consortium/v2/finality/consortium_header_test.go
- consortium-v2: define MarshalJSON on a non-pointer ValidatorWithBlsPub
We want json.Marshal to invoke our custom MarshalJSON when be called with
non-pointer ValidatorWithBlsPub. In order to do that, we need to define
MarshalJSON on a non-pointer receiver.
- consortium-v2: add missing weight field to our customized json marshal
=> consortium-v2: add missing weight field to our customized json marshal

core/blockchain.go, core/vm/evm.go, core/vm/evm_test.go
using counter variable, which count number of opcodes called, to move the newly added record to corresponding position
=> evm: order InternalTransactions

consensus/consortium/common/contract.go, consensus/consortium/common/contract_test.go, consensus/consortium/generated_contracts/legacy_profile/legacy_profile.go
This commit adds a step to query profile id from consensus address to support the consensus change feature. It also switches the function call to get BLS public key to another function due to the breaking change in getId2Profile.
=> consortium-v2: support consensus address change in profile contract

cmd/utils/flags.go, consensus/consortium/main.go, consensus/consortium/v1/consortium.go, consensus/consortium/v2/consortium.go, eth/backend.go, eth/ethconfig/config.go, les/client.go
Currently, when import chain is used, we don't recognize the chain config to
create the consortium engine. This commit creates the consortium engine when it
is set in the chain config.
=> chaincmd: correctly create consortium engine in import chain

consensus/consensus.go, consensus/consortium/common/constants.go, consensus/consortium/common/contract.go, consensus/consortium/common/contract_test.go, consensus/consortium/common/mock_contract.go, consensus/consortium/common/utils.go, consensus/consortium/common/utils_test.go, consensus/consortium/generated_contracts/legacy_profile/legacy_profile.go, consensus/consortium/generated_contracts/staking/staking.go, consensus/consortium/main.go, consensus/consortium/v1/consortium.go, consensus/consortium/v2/api.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/finality/consortium_header.go, consensus/consortium/v2/finality/consortium_header_test.go, consensus/consortium/v2/snapshot.go, core/vote/vote_manager.go, core/vote/vote_pool_test.go, monitor/finality_vote.go, params/config.go
This branch is used for rotating validators development
=> consortium: implement rotating validators

consensus/consortium/v2/consortium.go, consensus/misc/eip1559.go, consensus/misc/eip1559_test.go, core/chain_makers.go, core/state_processor_test.go, eth/tracers/api_test.go, ethclient/ethclient_test.go, miner/worker.go
Currently, we choose to set basefee to 0 after London fork on Ronin, the basefee logic can be changed in future fork. Besides, at the London fork, we don't double the block gas limit.
=> consensus, miner: set the basefee to 0 after London fork

genesis/testnet.json, params/version.go
The hardfork is scheduled around 7:00 UTC May 23rd, 2024 at block 34871800 (https://app.roninchain.com/block/34871800)
=> genesis: add Tripp hardfork on testnet

genesis/testnet.json
The hardfork is scheduled around 7:00 UTC May 23rd, 2024 at block 27580600 (https://saigon-app.roninchain.com/block/27580600).
=> genesis: update Tripp hardfork on testnet

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go
Ensure checkpointValidators field in header's extradata is empty in non-period
block.
=> consortium-v2: ensure checkpointValidators is empty in non-period block

eth/handler.go, eth/protocols/eth/handshake.go, eth/protocols/eth/metrics.go, eth/protocols/snap/metrics.go, p2p/dial.go, p2p/discover/metrics.go, p2p/discover/table.go, p2p/discover/v4_udp.go, p2p/discover/v4_udp_test.go, p2p/discover/v5_udp.go, p2p/metrics.go, p2p/server.go, p2p/server_test.go
Referenced by https://github.com/ethereum/go-ethereum/pull/27621 and https://github.com/ethereum/go-ethereum/pull/27008 
**Description** 
This PR adds metrics for
*  The p2p dialer, which gives us visibility into the quality of the dial candidates given to us by our discovery methods ( Healthy of dial connections for showing failure related to multitude of reasons: wrong chain, too many peers, etc.) 
*  Trafic metrics for  discV4 and discV5 related to network usage. 
**Added Metrics**
* discover/bucket/{index}/count - the number of nodes in bucket index
* eth/protocols/eth/{ingress|egress}/handshake/error/peer - unexpected peer behavior
* eth/protocols/eth/{ingress|egress}/handshake/error/timeout - handshake timeout
* eth/protocols/eth/{ingress|egress}/handshake/error/network - wrong …
=> p2p,eth: add dial, eth handshakes and traffic metrics

consensus/consortium/common/constants.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go
Fix wrong parenthesis placement in non-epoch block check in verifyValidatorFieldsInExtraData which leads to incorrect check result.
=> consortium-v2: fix wrong parenthesis placement in non-epoch block check

genesis/testnet.json, params/config.go, params/version.go
The hardfork is scheduled around 7:00 UTC June 15th, 2024 at block 28231200
(https://saigon-app.roninchain.com/block/28231200).
=> genesis: update Aaron hardfork on testnet

cmd/ronin/main.go, consensus/consortium/common/types.go, consensus/consortium/v1/consortium.go, consensus/consortium/v2/consortium.go, eth/backend.go, eth/ethconfig/config.go, eth/protocols/snap/sort_test.go, eth/protocols/snap/sync.go, les/client.go, trie/sync.go
- consortium: avoid reading statedb in block header verification path
In snap sync, we only verify header without processing block transactions so the
statedb is not available. As a result, we need to avoid reading statedb in the
header verification path and must use the information from header instead.
This commit disables signer list verification in extra data of checkpoint block
header in consortium version 1 when snap/fast sync. In consortium version 2, at
the forked block, when getting the list of validators, we read this information
from header instead of contract, it is expected to behave the same as before.
This commit does not change the header verification process when full sync.
- eth/protocols/snap: fix problems due to idle-but-busy peers
Mark the peer as idle only when it …
=> consortium: enable snap sync on Ronin

core/state_transition.go, core/vm/logger.go, eth/tracers/internal/tracetest/testdata/prestate_tracer_with_diff_mode/sponsored_tx.json, eth/tracers/js/goja.go, eth/tracers/js/tracer_test.go, eth/tracers/logger/access_list_tracer.go, eth/tracers/logger/logger.go, eth/tracers/logger/logger_json.go, eth/tracers/native/call.go, eth/tracers/native/call_flat.go, eth/tracers/native/mux.go, eth/tracers/native/noop.go, eth/tracers/native/prestate.go
In sponsored transaction, payer of gas fee can be different from sender. This commit fixes the prestate tracer to correctly track the balance of payer and sender in sponsored transaction.
Test with a sponsored transaction:
```
{
"from": "0xc89e2d7e38eb36d5213c2c505edd2d8974cd8718",
"to": "0xc89e2d7e38eb36d5213c2c505edd2d8974cd8718",
"payer": "0xd24d87ddc1917165435b306aac68d99e0f49a3fa",
"value": "0x0",
"gas": "0x7530",
"gasPrice": "0x4a817c800",
}
```
Request:
```
{
"jsonrpc": "2.0",
"method": "debug_traceTransaction",
"params": [
"0xf4794f0301f3235bdbe6d68a775ec3191cae02e8125e3a43b7cbe8457cfc5287",
{
"tracer": "prestateTracer",
"tracerConfig": {
"diffMode": true
}
}
],
"id": 1
}
```
Before:
```
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"post": { …
```
=> tracers/prestate: fix the balance track of payer and sender

.github/workflows/evm-benchmark.yml, .github/workflows/test-pr.yml
This will enable dependency and build output cache by default.
=> github/workflows: bump action/setup-go to v5

cmd/bootnode/main.go, eth/backend.go, eth/protocols/eth/discovery.go, p2p/discover/common.go, p2p/discover/metrics.go, p2p/discover/table.go, p2p/discover/table_test.go, p2p/discover/table_util_test.go, p2p/discover/v4_udp.go, p2p/discover/v5_udp.go, p2p/discover/v5_udp_test.go, p2p/server.go
**Description**  
Node discovery filtering based on ENR records for Ronin Network
Current implementation of discovery protocol is chain agnostic and does not differentiate between different chains (ETH, Ronin, ...). The discover protocol currently gossips peers from networks with different chain ids. This causes a pretty significant slowdown during peer discovery.
Reference by  https://github.com/bnb-chain/bsc/pull/1320
Dial and Enr Filter ratio metrics for an RPC node in the recent 3 hour metrics 
Before 
After 
The filtering ratio is ~9x now. 
For the Dial Result 
The formula is 
```
sum(rate(p2p_dials_success{statefulset_kubernetes_io_pod_name=~"$pod"}[1m]) - rate(eth_protocols_eth_egress_handshake_error_forkid{statefulset_kubernetes_io_pod_name=~"$pod"}[1m]) - …
```
=> p2p/discover: apply enr filtering in discovery phase, fix minor logic in doRevalidate

core/state/location_cacl.go, core/state/location_cacl_test.go, core/state/statedb_utils.go, core/state/statedb_utils_test.go
IsAddressBlacklisted is a hot function as it is called at least twice when processing a transaction in block to check the sender, recipient address in legacy transaction and 1 more with payer address in sponsored transaction. This PR tries to reduce memory allocation in this function by avoiding converting back and forth through big.Int but write the bytes directly to slice.
go test -bench=BenchmarkIsAddressBlacklisted -benchtime=5s
Before this PR
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/state
BenchmarkIsAddressBlacklisted-8          3112669              1805 ns/op            1008 B/op         16 allocs/op
```
After this PR
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/state
cpu: …
```
=> core/state: reduce memory allocation in IsAddressBlacklisted

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go
We get this warning and error log
```
WARN [07-08|04:18:15.866] Fail to get snapshot at                  blockNumber=36,192,799 blockHash=c19608..2c657b err="unknown ancestor"
ERROR[07-08|04:18:15.866] Failed to get block                      number=36,192,799 hash=0xc19608d700837c8ab4c184791bc3522766a48efb5f2e7734b827b3f9382c657b
```
IsPeriodBlock can be called in verifyHeader path. In that path, the parents of currently verifying block may not be inserted into chain yet so querying the parent may fail. In some functions like snapshot which IsPeriodBlock uses have the parent list parameter to query parent blocks when they are not inserted into chain. This commit adds a new parent list parameter to IsPeriodBlock and passes the parent list when it is called in verifyHeader path.
=> consortium-v2: add parent list parameter to IsPeriodBlock

core/types/access_list_tx.go, core/types/blob_tx.go, core/types/blob_tx_test.go, core/types/dynamic_fee_tx.go, core/types/legacy_tx.go, core/types/sponsored_tx.go, core/types/transaction.go, core/types/transaction_signing.go, params/protocol_params.go, rlp/raw.go, rlp/raw_test.go
This PR introduces the blob transaction types as defined in EIP-4844, extending the generic transaction interface. A new signer is included, which incorporates BlobGasFeeCap and BlobHashes into the transaction digest. Additionally, the rlp module has been enhanced with new methods, BytesSize and StringSize, to compute the size of the encoded data. These methods are essential for calculating the RLP encoded data size of blob transactions.
=> core/types: add blob transaction type

consensus/consortium/v1/snapshot.go, consensus/consortium/v2/snapshot.go, core/rawdb/accessors_snapshot.go, core/rawdb/database.go, core/rawdb/schema.go
Currently, snapshot consortium storage operation is handled by directly interacting with database. This pr groups these operations and provides api interface to interact with snapshot consortium database.
=> core/rawdb, consensus: add api for snapshot consortium storage

core/types/transaction_signing.go
If the blockNumber is Cancun already, create and return the Cancun signer in MakeSigner.
=> core/types: add Cancun signer to MakeSigner

core/vm/consortium_precompiled_contracts.go, core/vm/consortium_precompiled_contracts_test.go, core/vm/contracts.go, core/vm/evm.go, core/vm/evm_test.go
precompile query is a hot function which is called in every call related opcode.
This commit tries to optimize this function by making the Consortium precompiled
contract mapping into global variable so that precompile query does not need to
dynamically allocate the mapping every time it is called.
~ go test -bench=BenchmarkConsortiumPrecompileQuery -benchtime=5s -tags=blst_enabled
Before:
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/vm
BenchmarkConsortiumPrecompileQuery-8     4216357              2402 ns/op            1166 B/op          9 allocs/op
```
After:
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/vm …
```
=> core/vm: change Consortium precompiled mapping into global variable

core/vm/evm.go
We move the log and transaction hash calculation inside the if, so that they are executed only when the opcode is registered in publish event.
=> core/vm: only log when the opcode is registered

core/vm/memory.go
- core/vm: remove unnecessary zero out memory
In Set32, the slice passed to WriteToSlice is guaranteed to be larger or equal
to 32 bytes. The WriteToSlice ensures to fill the first 32 bytes so it's
unnecessary to zero out first 32 bytes before passing to WriteToSlice.
- core/vm: optimize the mstore opcode with loop unrolling
Unroll the loop in WriteToArray32 manually to speed up the mstore opcode.
Benchmark with insertion sort
Machine information:
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/vm
~ perf stat go test -test.v -run=^$ -bench=BenchmarkInsertionSort -benchtime=100x
Before
```
BenchmarkInsertionSort
BenchmarkInsertionSort-8             100          72793386 ns/op
PASS
ok …
```
=> core/vm: optimize the mstore opcode with loop unrolling

core/rawdb/accessors_state.go
Commit 87c0ba92136a ("core, eth, les, trie: add a prefix to contract code (#21080)") on Ethereum changes the key scheme to save contract code. This makes the rawdb.ReadCode must query using both old and new scheme. However, Ronin starts after this commit, so all code is stored using new scheme. Remove the old scheme query to save 1 database read when read code.
=> rawdb: query contract code using new scheme only

cmd/devp2p/internal/ethtest/types.go, core/blockchain_reader.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/queue.go, eth/downloader/queue_test.go, eth/downloader/types.go, eth/fetcher/block_fetcher.go, eth/fetcher/block_fetcher_test.go, eth/handler.go, eth/handler_eth.go, eth/handler_eth_test.go, eth/protocols/eth/broadcast.go, eth/protocols/eth/handler.go, eth/protocols/eth/handler_test.go, eth/protocols/eth/handlers.go, eth/protocols/eth/peer.go, eth/protocols/eth/peer_test.go, eth/protocols/eth/protocol.go
This PR is to:
- Cherry-pick ETH68, which added `Types` and `Sizes` to `TransactionHashesPacket`. `Sizes` will be useful for blob transactions, which are large in size, as it helps prevent bandwidth overload in the network.
- Implement ETH100, adding new blob's field `Sidecars` to `BlockBodiesPacket` when broadcasting and receiving new blocks.
=> eth: add eth/68 and eth/100

consensus/clique/clique.go, consensus/clique/snapshot.go, consensus/consortium/v1/consortium.go, consensus/consortium/v1/snapshot.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/snapshot.go, consensus/ethash/ethash.go, core/blockchain.go, core/blockchain_reader.go, core/headerchain.go, core/state/database.go, crypto/bls/blst/public_key.go, eth/gasprice/feehistory.go, eth/gasprice/gasprice.go, go.mod, go.sum, les/vflux/server/clientdb.go, light/lightchain.go, miner/worker.go, monitor/double_sign.go, monitor/finality_vote.go, p2p/discover/v5wire/session.go, p2p/dnsdisc/client.go
golang-lru version 2 supports generic in replacement of interface{} which makes it safer for development as type check is performed at compile time instead of runtime. This commit integrates Ronin with new package version.
=> all: bump github.com/hashicorp/golang-lru to version 2

eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/types.go, eth/fetcher/block_fetcher.go, eth/fetcher/block_fetcher_test.go, eth/handler.go
Call `VerifyBlobHeader` when importing new blocks in `fetcher` and `downloader`
=> eth: Add import block blob check

core/vm/contracts.go, core/vm/contracts_test.go
In commit 268d950147 ("core/vm: change Consortium precompiled mapping into global variable"), we mistakenly copy the Byzantium precompiled contracts to Istanbul and add blake2F at address 0x9 only. This is incorrect as the bn256 precompiled contracts at 0x6, 0x7, 0x8 are changed too. This commit fixes Istanbul precompiled contracts to have correct bn256 version.
=> core/vm: correct the Istanbul bn256 precompiled contracts

eth/sync.go
When finishing syncing, we only broadcast the head block hash to network (argument propagate = false when calling BroadcastBlock), so the sidecars are not used. Therefore, this commit removes the redundant sidecar read.
=> eth: remove redundant sidecar read

consensus/consortium/common/contract.go, consensus/consortium/common/contract_test.go, core/state/statedb.go
In 576852519 ("core/state: remove newAccessList in SetTxContext"), we remove the access list reset in SetTxContext because later in statedb.Prepare we already reset the list. However, system transaction does not call to statedb.Prepare before processing transaction. This results in a consensus breaking change. This commit create a new access list reset function and adds to system transaction path to fix the issue. Moreover, we add the statedb.Prepare call to system transaction path after Shanghai to make EIP-3651: warm coinbase and EIP-1153 - Transient storage opcodes work correctly in system transaction.
=> consortium-v2: prepare access list and transient storage in system transaction

eth/handler_eth_test.go, eth/protocols/eth/handlers.go, eth/protocols/eth/protocol.go
Add length check and reject BlockBodiesPacket100 with sidecars' length are not
either 0 or the same as number of blocks.
=> eth: add length check for sidecars in BlockBodiesPacket100

consensus/consortium/common/contract.go
Currently, the error when system transaction in the received block is different from the local calculation does not show the transaction in received block information. This makes it quite hard to debug. This commit adds these information to the error.
=> consortium-v2: make the system transaction mismatch error more verbose

eth/fetcher/block_fetcher.go
As after block/sidecar is imported into local chain, only block hash is broadcasted to peers, hence, we can emit passing the sidecars to broadcastBlock function.
=> eth/fetcher: remove sidecars pass while broadcasting block hash

consensus/clique/clique.go, consensus/consensus.go, consensus/consortium/main.go, consensus/consortium/v1/consortium.go, consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/ethash/consensus.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/types.go, eth/fetcher/block_fetcher.go, eth/fetcher/block_fetcher_test.go
The verify blob header function is primarily used during block fetching and downloading. Since its blob sidecar output is unused, we can eliminate it, transforming the function into a pure verification check.
=> consortium, eth: remove unused blob sidecars from verify blob header function

miner/worker.go, miner/worker_test.go
Blob sidecars should be discarded when commit new blob transaction, creating sidecars-free new mined block.
=> miner: remove attached sidecars when commit new blob transaction

miner/worker.go, miner/worker_test.go
There is a case where a blob transaction returned from txpool pending transaction query is evicted before commit. This leads to transaction's lazy resolve returns nil. This commit adds the nil check to ensure the transaction is not evicted before committing.
=> miner/worker: check if the transaction is evicted before committing

core/vm/eips.go
In Ronin, currently we don't have commit 9393d1fb5d ("core/vm: Move interpreter.ReadOnly check into the opcode implementations"). So the readonly check is still in the main interpreter loop, not in the opcode implementation. This commit makes the TSTORE opcode consistent with that behavior in the other opcodes.
=> core/vm: move readOnly check outside the TSTORE opcode

eth/backend.go, eth/protocols/eth/discovery.go
The race detector reports the following data race
```
Read at 0x00c0014e60b4 by goroutine 4291:
github.com/ethereum/go-ethereum/core/forkid.newFilter.func1()
github.com/ethereum/go-ethereum/core/forkid/forkid.go:163 +0xf1
github.com/ethereum/go-ethereum/p2p.(*Server).setupDiscovery.func2()
github.com/ethereum/go-ethereum/p2p/server.go:615 +0x1a2
github.com/ethereum/go-ethereum/p2p/discover.(*Table).filterNode()
github.com/ethereum/go-ethereum/p2p/discover/table.go:585 +0x456
github.com/ethereum/go-ethereum/p2p/discover.(*Table).addSeenNodeSync()
github.com/ethereum/go-ethereum/p2p/discover/table.go:548 +0x1c4
github.com/ethereum/go-ethereum/p2p/discover.(*Table).addSeenNode.func1()
github.com/ethereum/go-ethereum/p2p/discover/table.go:527 +0x47
Previous write at …
```
=> p2p, eth: create ENR filtering earlier before p2p server starts

eth/gasestimator/gasestimator.go
This PR adds more condition for blob transaction path, preventing `call.BlobGasFeeCap()` being nil when send non-blob transaction.
=> eth/gasestimator: fix nil blob gas fee cap

rpc/handler.go
Currently, error when send raw blob tx ends up a long unused log of sidecars data, this pr removes this unused log data, and only print out format:
```
WARN [08-22|17:39:31.389] Served eth_sendRawTransaction            conn=[::1]:61565 elapsed=14.860042ms id=8
err="nonce too high: tx nonce 68, gapped nonce 65"
```
=> rpc: remove msg params when log rpc error

core/rawdb/chain_iterator.go, core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/freezer_batch.go, core/rawdb/freezer_table.go, core/rawdb/freezer_table_test.go
Currently, some fields (i.e., `frozen`) in rawdb packet are currently stored atomically but read non-atomically, causing a data race. As a result, one of our shadow nodes (with data race detector flag set) meets a race condition error.
```
Write at 0x00c0001fa280 by main goroutine:
sync/atomic.StoreInt64()
runtime/race_amd64.s:237 +0xb
sync/atomic.StoreUint64()
<autogenerated>:1 +0x1b
github.com/ethereum/go-ethereum/core/rawdb.(*freezerdb).TruncateAncients()
<autogenerated>:1 +0x67
github.com/ethereum/go-ethereum/node.(*closeTrackingDB).TruncateAncients()
<autogenerated>:1 +0x56
github.com/ethereum/go-ethereum/core.(*BlockChain).setHeadBeyondRoot.func2()
github.com/ethereum/go-ethereum/core/blockchain.go:728 +0xbb …
```
=> core/rawdb: use atomic int to prevent data race

core/types/blob_sidecar.go, core/types/blob_tx.go
Old rpc response for eth_getBlobSidecarsByHash
```
[
{
"Blobs": [],
"Commitments": [],
"Proofs": [],
"TxHash": ""
}
]
```
New response
```
[
{
"blobs": [],
"commitments": [],
"proofs": [],
"txHash": ""
}
]
```
_Easy to merge_
=> core/types: fix response uncapitalized blob sidecars

eth/protocols/eth/handler.go, eth/protocols/eth/handlers.go
Currently, blob size is not added when estimating block bodies answer packet. Therefore, a node can try to create a block bodies answer packet that is bigger the maximum limit (10 MB in eth protocol, 16 MB in rlpx). This commit adds the blob size to correctly track the block bodies answer packet's size.
=> eth: add the blob size when estimating block bodies answer packet

consensus/misc/eip1559/eip1559.go, consensus/misc/eip1559/eip1559_test.go, core/state_processor_test.go, core/state_transition.go, params/config.go, params/protocol_params.go
After London fork, we always set base fee to 0. This commit implements REP-0022: Enable base fee on Ronin
(https://github.com/ronin-chain/REPs/blob/main/REP-0022/REP-0022.md) to enable base fee calculation and transfer that fee to treasury after Venoki fork.
=> consensus, core: enable base fee after Venoki fork

internal/flags/helpers.go
```
> ./build/bin/ronin account
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10035aa]
goroutine 1 [running]:
github.com/ethereum/go-ethereum/internal/flags.MigrateGlobalFlags.func2.1(0xc0004eeec0)
github.com/ethereum/go-ethereum/internal/flags/helpers.go:83 +0x2a
github.com/urfave/cli/v2.(*Command).Run(0x29b36c0, 0xc0004eeec0, {0xc0006da160, 0x1, 0x1})
github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x97d
github.com/urfave/cli/v2.(*Command).Run(0xc0005eec60, 0xc0004cc080, {0xc000156000, 0x2, 0x2})
github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xbb7
github.com/urfave/cli/v2.(*App).RunContext(0xc00028da00, {0x1d92a58, 0x2c71480}, {0xc000156000, 0x2, 0x2})
github.com/urfave/cli/v2@v2.27.1/app.go:337 …
```
=> cli: skip migrating global flags for nil action

go.mod, go.sum
The pyroscope-go v1.1.1 uses godeltaprof v0.1.6 which sets the upper bound of Go version 1.22, so it cannot be built with Go 1.23. pyroscope-go v1.1.2 uses godeltaprof v0.1.8 which is built successfully with Go 1.23.
=> go.mod: bump pyroscope-go to v1.1.2

core/blockchain.go, core/blockchain_reader.go
enableAdditionalChainEvent is true in subscriber only to publish additional information including opcode execution. Currently, in insertChain, we already enableAdditionalChainEvent the before capturing opcode execution. However, in system transaction, we always capture opcode execution by using bc.OpEvents without checking enableAdditionalChainEvent. This commit moves the enableAdditionalChainEvent check into bc.OpEvents so that opcode execution is captured only when enableAdditionalChainEvent is true.
=> core: capture opcode execution in subscriber only

consensus/consortium/common/constants.go, consensus/consortium/common/contract.go
System transaction is a special transaction which is not constrained by the gas pool block limit. So currently, system transaction has a very high gas limit (i.e. MaxUint64 / 2). It is unnecessary because actual gas used is much lower and must be fewer than block gas limit. Besides, the high transaction gas limit also causes issues with developer tools.
This commit reduces the system transaction gas limit to 50_000_000 after Venoki. The change to system transaction in getTransactionOpts requires the Venoki hardfork. Other places where the high gas limit is used to call contract do not require hardfork logic because we assume that 50_000_000 is enough to perform these contract calls and the results of contract calls do not depend on the provided gas limit.
=> consortium-v2: reduce the system transaction's gas limit after Venoki

crypto/kzg4844/kzg4844.go, crypto/kzg4844/kzg4844_test.go
There are 2 places that verify blob proof: transaction pool when a blob
transaction is added, blob sidecar of a new block. The blob in a blob
transaction in pool is very likely to be included in a mined block in the near
future. So we can cache the verification result to avoid double verification.
The benchmark results show significant improvement in cache hit case and
insignificant overhead in cache miss case.
Benchmark with cache hit
```
│    old.txt     │               new.txt                │
│     sec/op     │    sec/op     vs base                │
GoKZGVerifyBlobProof-8   2813.49µ ± 15%   19.74µ ± 17%  -99.30% (p=0.000 n=10)
```
Benchmark with cache miss
```
│   old.txt   │            new.txt            │
│   sec/op    │   sec/op     vs base          │ …
```
=> crypto/kzg4844: cache the verify blob proof result

core/blockchain_test.go, core/state_transition.go, core/txpool/legacypool/legacypool_test.go, core/txpool/validation.go
After Venoki, when base fee is enabled, remove the restriction that gasTipCap must be the same as gasFeeCap in sponsored transaction.
=> core: allow different gasTipCap and gasFeeCap after Venoki

core/txpool/blobpool/blobpool.go, core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go, core/txpool/validation.go
effectiveTip = min(tipcap, feecap - basefee), so the too low feecap can make the effectiveTip not enough to cover the pool's required tip. This commit adds a check to ensure feecap - minBaseFee is not lower the the pool's required tip.
=> txpool: ensure the max tip based on gas fee cap is high enough

core/state/database.go, core/state/metrics.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/state_object.go, core/state/statedb.go, eth/protocols/snap/sync_test.go, light/postprocess.go, light/trie.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/committer.go, trie/database.go, trie/iterator.go, trie/iterator_test.go, trie/nodeset.go, trie/proof.go, trie/secure_trie.go, trie/secure_trie_test.go, trie/sync_test.go, trie/trie.go, trie/trie_test.go, trie/utils_test.go
Reference in https://github.com/ethereum/go-ethereum/pull/25320.
It's implementing PR prepare for next implementing Path based. 
this PR is submitted to adjust the commit procedure. Now all the dirty nodes of a trie will be encapsulated in a struct called nodeSet for return. Multiple nodeSets can be merged together as a MergedNodeSet. Eventually the MergedNodeSet will be submitted to in-memory database as a whole to represent the state transition from block to block.
=> core, trie: rework trie commiter

cmd/devp2p/internal/ethtest/chain.go, cmd/evm/runner.go, cmd/faucet/faucet.go, consensus/clique/snapshot_test.go, core/blockchain.go, core/blockchain_test.go, core/chain_makers.go, core/genesis.go, core/genesis_test.go, core/rawdb/accessors_metadata.go, core/rawdb/database.go, core/rawdb/schema.go, eth/catalyst/api_test.go, eth/downloader/queue_test.go, eth/downloader/testchain_test.go, eth/fetcher/block_fetcher_test.go, eth/filters/filter_test.go, eth/gasprice/gasprice_test.go, ethclient/ethclient_test.go, ethclient/gethclient/gethclient_test.go, les/downloader/queue_test.go, les/downloader/testchain_test.go, les/fetcher/block_fetcher_test.go, les/peer_test.go, tests/state_test.go, tests/state_test_util.go
This PR refers to the 2 following PRs:
- https://github.com/ethereum/go-ethereum/pull/24460: allow recommitting genesis state in case of rewinding to it. The current code assume genesis state is always in the database, but PBSS might overwrite the old states.
- https://github.com/ethereum/go-ethereum/pull/25473: rework a few things:
- - `ToBlock` is now only used to generate genesis block, since we have `Flush` to write to db
- - Remove `GenesisBlockForTesting`
=> all: rework genesis api

core/state_transition.go, eth/tracers/native/prestate.go
- core: skip gas check for system transaction when tracing
As system transaction has 0 gas price, it does not pass the check that gas price
must be greater or equal to base fee when base fee is not 0. Skip gas check for
system transaction in TransitionDb, system transaction will go through
TransitionDb only in tracing path not in normal transaction processing path.
- eth/tracers: fix balance tracking in prestate tracer after Venoki
Add ronin treasury to balance tracking after Venoki as base fee and blob fee are
transferred to it. The blob fee is subtracted from sender's balance added to
ronin treasury's balance in buyGas which is before the CaptureStart hook. So we
need to fix these balances up to get the correct balance before the transaction
happens.
=> eth/tracers: fix system transaction and prestate tracer after Venoki

cmd/devp2p/internal/ethtest/helpers.go, cmd/devp2p/internal/ethtest/suite.go, cmd/devp2p/internal/ethtest/transaction.go, eth/fetcher/tx_fetcher.go, eth/fetcher/tx_fetcher_test.go, eth/handler.go, eth/handler_eth.go, tests/fuzzers/txfetcher/txfetcher_fuzzer.go
This PR should be rebased and merged to keep the history.
List of commits:
These 2 commits do not relate to blob transactions, are added to cherry pick the below commits cleanly
- eth/fetcher: throttle peers which deliver many invalid transactions
- eth/fetcher: allow underpriced transactions in after timeout
Validate new transaction metadata in eth/68 and use it to throttle fetch request
- eth: enforce announcement metadatas and drop peers violating the protocol
- eth/fetcher: throttle tx fetches to 128KB responses
Fetch blob transaction earlier and mitigation for nonce gap when fetching blob transactions
- eth/fetcher: fix blob transaction propagation
More details are available in each commit message.
=> eth/fetcher: cherry pick changes from go-ethereum to handle blob transaction

eth/backend.go, eth/handler.go, eth/handler_eth.go
Only announce transaction hash with big transaction and blob transaction
- eth: send big transactions by announce/retrieve only
- eth: send blob transactions by announce/retrieve only
Mitigation to nonce gap issue (if a peer receives full broadcasted transaction from a sender, later transaction from the same sender is also broadcasted)
- eth: make transaction propagation paths in the network deterministic
=> eth: cherry pick transaction broadcast improvement

core/state/sync.go, core/state/sync_test.go, eth/downloader/statesync.go, eth/protocols/snap/sort_test.go, eth/protocols/snap/sync.go, les/downloader/statesync.go, trie/committer.go, trie/sync.go, trie/sync_test.go, trie/trie.go, trie/trie_test.go
Reference: https://github.com/ethereum/go-ethereum/pull/24898
=> core, eth: rework snap sync

cmd/ronin/dbcmd.go, cmd/utils/flags.go, core/rawdb/accessors_chain.go, core/rawdb/ancient_scheme.go, core/rawdb/chain_freezer.go, core/rawdb/chain_iterator.go, core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/freezer_table.go, core/rawdb/freezer_table_test.go, core/rawdb/schema.go, ethdb/database.go, node/node.go
Reference https://github.com/ethereum/go-ethereum/pull/25487 .
Before The chain segment should be stored in <chaindata/ancient>. Now it will locate in <chaindata/ancient/chain> in case u start the new disk, otherwise support backward compatibility 
Handling  main idea is here. 
```
if !common.FileExist(freezer) {
if !common.FileExist(ancient) {
// The entire ancient store is not initialized, still use the sub
// folder for initialization.
} else {
// Ancient root is already initialized, then we hold the assumption
// that chain freezer is also initialized and located in root folder.
// In this case fallback to legacy location.
freezer = ancient
log.Info("Found legacy ancient chain path", "location", ancient)
}
}
```
=> Change ancient chain segments from root ancient to sub folders

core/rawdb/accessors_chain.go
commit https://github.com/ethereum/go-ethereum/commit/66a908c5e87a4f38c0507ae2c7e53b242deb7128.
Recursive read-locking is prohibited in RWMutex which can lead to deadlock. ReadCanonicalHash internally calls ReadAncients which cause recursive read-locking. This commit reads the block directly from leveldb/pebbledb in case block is not in ancient without using helper function ReadCanonicalHash.
=> core/rawdb: fix double-lock causing hang (#24189)

core/blockchain.go, core/rawdb/ancient_scheme.go, core/rawdb/ancient_utils.go, core/rawdb/chain_freezer.go, core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/table.go, core/state/state_object.go, core/state/statedb.go, ethdb/database.go
https://github.com/ethereum/go-ethereum/pull/25896 Reference, right now we need to implement the deletion tail feature, I leave for returning 0, and nil for err, when calling tail function in Inspecting
=> Make db inspector for extending multiple ancient stores

core/txpool/blobpool/blobpool.go
commit https://github.com/ethereum/go-ethereum/commit/0dd7e82c0aef3c27303b4a7b30016790dda949d4.
This situation(`len(txs) == 0`) rarely occurs, but if it does, it will panic.
=> core/txpool/blobpool: avoid possible zero index panic (#30430)

eth/api.go
sidecar slice is used to store the sidecars of the imported batch. We need to empty that slice when finishing importing a batch.
=> api: empty the sidecar slice after every batch

.github/workflows/evm-benchmark.yml, script/benchstat.sh
Currently, all iterations of the benchmark for old commit run before the one for new commit. This can make the noise not evenly distributed across 2 benchmark runs (e.g. the machine heats up too much after running all iterations the old benchmark). This commit introduces interleave mode when running benchmark where each iteration of benchmark for old commit is followed by an iteration of benchmark for new one then back to an iteration of benchmark for old one.
=> script/benchstat: introduce interleave mode when running benchmark

trie/committer.go, trie/database.go, trie/iterator.go, trie/node.go, trie/nodeset.go, trie/proof.go, trie/trie.go, trie/trie_reader.go
Reference: https://github.com/ethereum/go-ethereum/pull/26813
This PR generalize the trie database for later use of Verkle Tree
Some changes:
- database.go: `cacheNode` no longer stores node as a whole node, but the encoded bytes instead
- database.go: move resolver logic to committer, since it is specific for MPT
- trie_reader.go: only provide retrieving encoded node now
=> core, trie: rework trie database

core/txpool/blobpool/blobpool.go
commit https://github.com/ethereum/go-ethereum/commit/0a21cb4d21a254cc87c7ecc50462f8c2735a302f.
Use types.Sender(signer, tx) to utilize the transaction's sender cache and avoid repeated address recover.
=> core/txpool/blobpool: use types.Sender instead of signer.Sender (#30473)

core/state/dump.go, core/state/journal.go, core/state/metrics.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/state_object.go, core/state/state_test.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, core/state/statedb_test.go, core/types/state_account.go, eth/protocols/snap/sync_test.go, light/postprocess.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, trie/database.go, trie/iterator_test.go, trie/sync_test.go, trie/tracer_test.go, trie/trie_test.go, trie/trienode/node.go, trie/triestate/state.go
Reference: https://github.com/ethereum/go-ethereum/pull/27349
This PR is for tracking state changes in stateDB. The tracked changes will later be used in PBSS to generate the history data.
Changes:
- trie/triestate/state.go: create struct `Set` representing the state changes that will be tracked. There will be pairs of values before and after being changed.
- trie/database_wrap: change name to database; `database.Update()` now take in the tracked state changes, which will later be used in PBSS.
- core/state_object: `stateObject` represents an account being updated. Now, `origin`, which represents the account before changes, is added for keeping track of changes. This `origin` will be updated to the current account only after committing.
- core/statedb: 
- - accounts/storages origins and …
=> trie, core: track state changes in statedb

cmd/evm/internal/t8ntool/execution.go, cmd/evm/runner.go, core/blockchain.go, core/blockchain_test.go, core/chain_makers.go, core/genesis.go, core/state/dump.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/state_object.go, core/state/state_test.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, core/state/statedb_test.go, core/state/sync_test.go, core/txpool/blobpool/blobpool_test.go, eth/api_test.go, eth/protocols/snap/sync_test.go, eth/state_accessor.go, light/postprocess.go, tests/fuzzers/stacktrie/trie_fuzzer.go, tests/fuzzers/trie/trie-fuzzer.go, tests/state_test_util.go, trie/database.go, trie/iterator_test.go, trie/sync_test.go, trie/tracer_test.go, trie/trie_test.go
References: https://github.com/ethereum/go-ethereum/pull/27753
Changes:
- clean up: `stateObject` already contains the db, so there is no need to pass the db in its methods
- `statedb.Commit()` now also pass the block number, which will be later used for PBSS to build history data
=> core, trie: Expose block number to statedb

core/state/journal.go, core/state/state_object.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, trie/committer.go, trie/database.go, trie/database_test.go, trie/tracer.go, trie/trie.go, trie/trie_reader.go, trie/trie_test.go, trie/triedb/hashdb/database.go, trie/triedb/pathdb/database.go, trie/triedb/pathdb/database_test.go, trie/triedb/pathdb/difflayer.go, trie/triedb/pathdb/difflayer_test.go, trie/triedb/pathdb/disklayer.go, trie/triedb/pathdb/errors.go, trie/triedb/pathdb/history.go, trie/triedb/pathdb/history_test.go, trie/triedb/pathdb/journal.go, trie/triedb/pathdb/layertree.go, trie/triedb/pathdb/metrics.go, trie/triedb/pathdb/nodebuffer.go, trie/triedb/pathdb/testutils.go, trie/trienode/node.go, trie/triestate/state.go
Changes:
- trie/trienode: Remove `NodeWithPrev`, use `Node` instead since we will not use the prev value anyway; function for create delete node (hash = 0, for marking deleted nodes)
- trie/triestate: track changes by node address instead of address hash; function for creating new Set
- trie/database: add block and state changes fields when calling Update(); init cleans cache in the lower database (hashdb) instead of the wrapper database
- trie/tracer, trie: the process of marking deleted nodes will be done in the trie component now, and the tracer just returns the deleted nodes. This change generalized the tracer.
=> all: clean up overall structure, preparing for path-based

core/blockchain.go, core/rawdb/accessors_chain_test.go, core/rawdb/accessors_indexes_test.go, core/rawdb/accessors_state.go, core/rawdb/accessors_trie.go, core/rawdb/ancient_scheme.go, core/rawdb/chain_iterator_test.go, core/rawdb/database.go, core/rawdb/freezer.go, core/rawdb/freezer_resettable.go, core/rawdb/freezer_resettable_test.go, core/rawdb/freezer_table.go, core/rawdb/freezer_test.go, core/rawdb/schema.go, core/rawdb/table.go, ethdb/database.go
Reference: https://github.com/ethereum/go-ethereum/pull/26324
=>  rawdb: implement freezer resettable & state freezer 

script/overlayfs_chaindata.sh
overlayfs can used to quickly rollback all the changes we make to the chaindata when testing.
Example usage:
```
> pwd
/home/test
> ls
chaindata
> overlayfs_chaindata.sh -d /home/test
+ cd /home/test/
+ mkdir -p upper
+ mkdir -p workdir
+ mv chaindata orig_chaindata
+ mkdir -p chaindata
+ mount -t overlay overlay -olowerdir=./orig_chaindata,upperdir=./upper,workdir=./workdir chaindata
\# make changes to chaindata
...
\# rollback to original chaindata
> overlayfs_chaindata.sh -d /home/test -c
+ cd /home/minh_bui_skymavis_com/
+ umount ./chaindata
+ rm -rf chaindata
+ rm -rf upper
+ rm -rf workdir
+ mv orig_chaindata chaindata
```
=> script: add overlayfs setup script for chaindata

core/blockchain.go, core/blockchain_test.go
The default blob prune period is 518400-block long, which makes unit test take so much time to generate and import those blocks. This commit adds a helper function to override the default value which can be used by tests.
=> core: add a helper function to override the default prune period

core/blockchain.go, core/blockchain_test.go, core/vote/vote_pool.go, core/vote/vote_pool_test.go, internal/cmdtest/test_cmd.go, p2p/discover/table_test.go
- core: fix data race in TestInsertChainWithSidecars
We get this data race when running tests
```
Write at 0x00c0117bbf40 by goroutine 77211:
github.com/ethereum/go-ethereum/core.TestInsertChainWithSidecars()
/home/runner/work/ronin/ronin/core/blockchain_test.go:4215 +0x49fd
testing.tRunner()
/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1576 +0x216
testing.(*T).Run.func1()
/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1629 +0x47
Previous write at 0x00c0117bbf40 by goroutine 82133:
github.com/ethereum/go-ethereum/core.TestInsertChainWithSidecars.func6.1()
/home/runner/work/ronin/ronin/core/blockchain_test.go:4179 +0x5a4
testing.tRunner()
/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1576 +0x216
testing.(*T).Run.func1() …
```
=> core: fix data races in unit tests

cmd/utils/flags.go, consensus/consortium/v1/consortium.go, core/rawdb/ancient_scheme.go, docker/chainnode/entrypoint.sh, eth/backend.go
* Fix missing passing scheme when init genesis
* Avoid referencing same object when passing parents in cosortium v1
=> Fix missing passing scheme when init genesis and avoid referencing same object when passing parents in cosortium v1

core/blockchain.go, eth/downloader/downloader.go
References:
- eth/downloader: prevent pivot moves after state commit https://github.com/ethereum/go-ethereum/pull/28126
- core, eth/downloader: fix genesis state missing due to state sync https://github.com/ethereum/go-ethereum/pull/28124
=> core, eth/downloader: pbss fix release v1.13.1

.github/workflows/evm-benchmark.yml
In 0eb8e918e ("script/benchstat: introduce interleave mode when running benchmark"), we change the benchstat script's argument. This commit makes the workflow use the new argument.
=> github/workflows: correct the argument provided to benchstat

rlp/encbuffer.go, rlp/encode.go, rlp/encode_test.go, trie/committer.go, trie/hasher.go, trie/iterator.go, trie/node.go, trie/node_enc.go, trie/proof.go, trie/stacktrie.go, trie/trie_test.go
commit https://github.com/ethereum/go-ethereum/commit/65ed1a6871569ce616f18d69f6ec8cfbec85c1f2.
This change speeds up trie hashing and all other activities that require RLP encoding of trie nodes by approximately 20%. The speedup is achieved by avoiding reflection overhead during node encoding.
The interface type trie.node now contains a method 'encode' that works with rlp.EncoderBuffer. Management of EncoderBuffers is left to calling code. trie.hasher, which is pooled to avoid allocations, now maintains an EncoderBuffer. This means memory resources related to trie node encoding are tied to the hasher pool.
This also refactors some functions in rlp package.
```
goos: linux
goarch: amd64
│   old.txt    │               new.txt …
```
=> rlp, trie: faster trie node encoding (#24126)

accounts/abi/bind/backends/simulated.go, cmd/devp2p/internal/ethtest/suite_test.go, core/blockchain.go, core/rawdb/accessors_sync.go, core/rawdb/accessors_trie.go, core/rawdb/database.go, core/rawdb/schema.go, eth/api_backend.go, eth/backend.go, eth/downloader/downloader.go, eth/handler.go, eth/handler_eth.go, eth/handler_eth_test.go, eth/sync.go, miner/miner_test.go, trie/database.go, trie/sync.go, trie/sync_test.go, trie/triedb/pathdb/database.go, trie/triedb/pathdb/database_test.go, trie/triedb/pathdb/errors.go, trie/triedb/pathdb/journal.go
References:
- core, accounts, eth, trie: handle genesis state missing https://github.com/ethereum/go-ethereum/pull/28171
- trie: remove internal nodes between shortNode and child in path mode https://github.com/ethereum/go-ethereum/pull/28163
=> core, accounts, eth, trie: pbss fix release v1.13.2

core/rawdb/ancient_utils.go, core/rawdb/freezer_batch.go, core/rawdb/freezer_resettable.go, core/rawdb/freezer_table.go, core/rawdb/freezer_utils.go, trie/triedb/pathdb/database_test.go, trie/triedb/pathdb/disklayer.go, trie/triedb/pathdb/history.go, trie/triedb/pathdb/history_test.go
Referecences: 
- trie/triedb/pathdb, core/rawdb: enhance error message in freezer https://github.com/ethereum/go-ethereum/pull/28198
- trie/triedb/pathdb: improve dirty node flushing trigger https://github.com/ethereum/go-ethereum/pull/28426
- core/rawdb: fsync the index file after each freezer write https://github.com/ethereum/go-ethereum/pull/28483
=> trie/triedb/pathdb, core/rawdb: pbss fix release v1.13.5 (corner-cases in path scheme state management)

cmd/ronin/chaincmd.go, docker/chainnode/entrypoint.sh
Before this PR, when initializing genesis, the ancient db is not opened for writing the genesis state, results in data inconsistency in the ancient db. Therefore, when processing the next blocks, the following error occurred
```
CRIT [10-30|04:53:29.422] Failed to truncate state history freezer err="out of range, tail: 0, head: 0, target: 90000"
```
This PR simply open the ancient db for writing genesis state when initializing it.
=> cmd/ronin/chaincmd: open ancient freezer when init genesis

consensus/consortium/v1/consortium.go
Related to recent PR merged to path-base implementing https://github.com/axieinfinity/ronin/pull/614
> State sync overwrites the persistent state, and this action can disrupt states that reference the current persistent state. The appropriate solution in such a situation is to mark the entire trie database as unusable, which prevents any subsequent state reads, and raises a layer stale error if the read operation is done by the prev-created stale state. The trie database will remain in this state until the state sync process is completed, and a usable persistent state is assembled.
In the coming enhancements related to avoid disruption genesis data  in the snap sync with path schem enable. In the Ronin implementing, we have some functions for getting Validators from StateDB during snap …
=> [consortium-v1] Get list validators from genesis instead of statedb for snapsync.

core/rawdb/ancient_utils.go, core/rawdb/chain_freezer.go
Before 
```
Attaching to node
node    | INFO [11-06|17:14:43.375] Maximum peer count                       ETH=50 LES=0 total=50
node    | INFO [11-06|17:14:43.377] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
node    | INFO [11-06|17:14:43.386] Using pebble as the backing database
node    | INFO [11-06|17:14:43.387] Allocated cache and file handles         database=/ronin/data/ronin/chaindata cache=512.00MiB handles=524,288
node    | INFO [11-06|17:14:43.950] Opened ancient database                  database=/ronin/data/ronin/chaindata/ancient/chain readonly=true
node    | INFO [11-06|17:14:43.952] State scheme set to already existing     scheme=path
node    | INFO [11-06|17:14:43.954] Set global gas cap …
```
=> cmd, rawdb: Fix db inspect command when overwriting the tail method in chainfreezer.

core/rawdb/accessors_trie.go, core/rawdb/schema.go, core/rawdb/schema_test.go, trie/triedb/pathdb/database.go, trie/triedb/pathdb/nodebuffer.go
References:
- https://github.com/ethereum/go-ethereum/pull/28724 (v1.13.8 continue)
- https://github.com/ethereum/go-ethereum/pull/29106
- https://github.com/ethereum/go-ethereum/pull/29107
=> core, triedb/pathdb: pbss fix release v1.13.8 (continue) and v1.14.0

eth/protocols/snap/sync_test.go
Reference: https://github.com/ethereum/go-ethereum/pull/25532
Before PBSS, in the snap sync tests, there are no changes to the account trie, so it is acceptable for the peers to use the same account trie. However, PBSS added a tracer that also traces the accessed nodes, leading to the race condition.
This PR is to assign each peer with a copy of the account trie.
=> protocols/snap/sync_test: each peer have a different account trie

cmd/ronin/dbcmd.go, core/rawdb/ancient_scheme.go, core/rawdb/ancient_utils.go, core/rawdb/database.go, ethdb/dbtest/testsuite.go, trie/sync.go, trie/sync_test.go, trie/triedb/pathdb/database.go
References:
- https://github.com/ethereum/go-ethereum/pull/28595 (v1.13.6)
- https://github.com/ethereum/go-ethereum/pull/28718 (v1.13.8)
=> core, cmd, trie: pbss fix release v1.13.6 and v1.13.8

consensus/consortium/v2/consortium.go
IsPeriodBlock uses the block header's timestamp to determine if the block is in new period. So we need to move the block header's timestamp calculation before the logic that calls IsPeriodBlock.
=> consortium-v2: move the block timestamp calculation before IsPeriodBlock

consensus/consortium/v2/snapshot.go, params/config.go
This is a refactor commit that explicitly name some hard to understand conditional checks in snapshot's apply. It also adds more comments to snapshot fields.
=> consortium-v2: explicitly name conditional check in snapshot's apply

consensus/consortium/v2/consortium_test.go
This PR is an alternative for https://github.com/axieinfinity/ronin/pull/612
Before this PR, in `TestIsPeriodBlock` and `TestIsTrippEffective`, the chain of blocks is inserted while it still includes some previously inserted blocks, causing the below error when running on path scheme.
Potential reason:
- There are still logics for correctly handle inserting inserted blocks.
- However, in pathdb, the blocks older than 128 blocks are not directly retrievable from the layer tree, which are already capped to the disk layer. (there are 128 diff layers) => the parent of the being-inserted block cannot be retrieved for processing.
- In hashdb, the old blocks can still be retrieved from disk.
- Therefore, in this 2 tests, the number of blocks inserted are too large to be retrieve, causing the …
=> v2/consortium_test: fix for pbss: do not insert inserted blocks

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/finality/consortium_header.go
This commit refactors the logic that checks extraData's validator information with contract data into a separate function. It also adds more information in the error cases.
=> consortium-v2: move extraData check with contract into a function

core/vm/evm.go, params/config.go
The Consortium precompiled contract is used in the last block of version 1 before the version 2 is enabled. So we need to enable the Consortium precompiled earlier.
=> core/vm: enable Consortium precompiled contract at the last block of v1

consensus/consortium/v2/consortium.go
In commit 584db0f668 ("consortium-v2: move extraData check with contract into a function"), we refactor the code and mistakenly return even if we successfully verify extraData. Fix it by checking the error and only return if there is an error when verifying extraData.
=> consortium-v2: only return when failing to verify extraData

core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go
commit https://github.com/ethereum/go-ethereum/commit/14a1e96b68386d28b26e82f4dae2a86062d3b355.
This change adds a check to ensure that transactions added to the legacy pool are not treated as 'locals' if the global locals-management has been disabled.
This change makes the pool enforce the --txpool.nolocals setting.
=> core/txpool/legacypool: respect nolocals-setting (#28435)

ethclient/ethclient.go, internal/ethapi/api.go, internal/web3ext/web3ext.go
commit https://github.com/ethereum/go-ethereum/commit/f1801a9feda8f81532c92077d2c9a8b785fd699b.
The response is the same as eth_getTransactionReceipt but allow user to get all receipts in a block instead of having to query each transaction as eth_getTransactionReceipt.
=> internal/ethapi: implement eth_getBlockReceipts (#27702)

core/types/block.go, core/vm/consortium_precompiled_contracts.go, core/vm/consortium_precompiled_contracts_test.go
After Venoki, these fields are added into block's header: BaseFee, BlodGasUsed, ExceedBlobGas.
We need to add them into the double sign verification process to make sure the logic up to date.
The separated struct due to lack off optional and null support of contract Abi
=> core/vm: Add Venoki header's fields when verify double sign

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go, consensus/consortium/v2/snapshot.go
Currently, Ronin detects the start of new period is the first block of an epoch
where that block's timestamp is on the different date from first block of
previous epoch. However, in contract, the start of new period is the first block
of epoch where the parent of it (the last block of previous epoch)'s timestamp
is on the different date from the last block of "previous previous" epoch. In
this commit, we change the Ronin logic to be consistent with contract after
Venoki hardfork.
=> consortium-v2: make the period definition consistent with contract

core/chain_makers.go, eth/api_backend.go, eth/gasprice/feehistory.go, eth/gasprice/feehistory_test.go, eth/gasprice/gasprice_test.go, internal/ethapi/api.go, internal/ethapi/api_test.go, internal/ethapi/backend.go, internal/jsre/deps/web3.js, les/api_backend.go
picked from https://github.com/ethereum/go-ethereum/commit/1ec7af261223d6dad9370ee8263f86347b190bab
=> internal/ethapi: implement eth_blobBaseFee and blob fields to eth_feeHistory

cmd/ronin/dbcmd.go, p2p/enode/nodedb.go
```
INFO [12-18|16:52:14.243] Node                                     ID=0165f3d3dd623633 IP=34.132.208.47 UDP=30303 TCP=30303 eth="{ForkID:{Hash:[202 131 6 42] Next:0} Tail:[]}"
INFO [12-18|16:52:14.243] Node                                     ID=06234c04be2bd692 IP=34.69.23.166  UDP=30303 TCP=30303 eth="{ForkID:{Hash:[202 131 6 42] Next:0} Tail:[]}"
INFO [12-18|16:52:14.243] Node                                     ID=093b8430a0f45b6e IP=162.120.70.174 UDP=30303 TCP=30303 eth="{ForkID:{Hash:[202 131 6 42] Next:0} Tail:[]}"
INFO [12-18|16:52:14.243] Node                                     ID=095bb3097e9aa2dd IP=148.251.246.239 UDP=14503 TCP=14503 eth="{ForkID:{Hash:[202 131 6 42] Next:0} Tail:[]}"
INFO [12-18|16:52:14.243] Node                                     ID=09eb0cf1ffebd62f …
```
=> cmd/db: Add inspect enode db

core/vm/memory.go, go.mod, go.sum
commit https://github.com/ethereum/go-ethereum/commit/5c58612e12a5131233be5efc9aa9ff55aac4538a.
Updates geth to use the uint256 v1.3.2, and use faster memory-writer to speed up MSTORE.
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/vm
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
OpMstore-8   18.18n ± 8%   12.58n ± 8%  -30.76% (p=0.000 n=10)
```
Link: https://github.com/holiman/uint256/pull/190
=> core/vm, go.mod: update uint256 and use faster method to write to memory (#30868)

script/bootstrap_local_chain.sh
```
INFO [12-25|17:11:00.048] Commit new mining work                   number=11 sealhash=921cc9..8bde0b uncles=0 txs=0 gas=0 fees=0 elapsed=2.828ms
INFO [12-25|17:11:00.048] Sealing block with                       number=11 delay=4.951728s headerDifficulty=3 val=0x1Feac05E5aE02CB3F7A25E010F70fec4aC6e2272 txs=0
INFO [12-25|17:11:00.103] New local node record                    seq=1,735,121,428,494 id=b152b046f7dbc277 ip=127.0.0.1 udp=30305 tcp=30305
INFO [12-25|17:11:03.017] SubmitBlockReward
INFO [12-25|17:11:03.033] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=16.519ms    mgasps=0.000 number=11 hash=fe8a48..04fdbb dirty=0.00B
INFO [12-25|17:11:03.034] SubmitBlockReward
INFO [12-25|17:11:03.034] Commit new mining work                   number=12 …
```
=> script: refactor avoiding duplicating logic in boostrap local chain

.github/workflows/evm-benchmark.yml, .github/workflows/test-pr.yml, Dockerfile, Dockerfile.alltools, go.mod, go.sum
Adapt with newer Go version to leverage the built-in tool and improve performance.
[Go 1.21](https://go.dev/blog/go1.21)
[Go 1.22](https://go.dev/blog/go1.22)
[Image](https://hub.docker.com/layers/library/golang/1.22.10-alpine3.21/images/sha256-8c11f5f33f701c83026a61006b1e7d05bc3335b2d70fe1bd41595d7c65a976f1 )
=> misc: upgrade go mod version, docker go and alpine version

consensus/consortium/v2/consortium.go, consensus/consortium/v2/consortium_test.go
This is the same as commit b718105228d9 ("consortium-v2: add parent list parameter to IsPeriodBlock") but with the IsTrippEffective function. The parent list is passed to this function when it is called in the VerifyHeader path.
=> consortium-v2: add parent list parameter to IsTrippEffective

core/vm/opcodes.go
commit https://github.com/ethereum/go-ethereum/commit/5b9a3ea9d2930eb2228c5203d1afe40776e70af3.
Noticed this omission while doing some work on goevmlab. We don't properly type some of the opcodes, but apparently implicit casting works in all the internal usecases.
This makes the debugger show the name of those missing type opcodes instead of just hexadecimal value.
=> core/vm: make all opcodes proper type (#30925)

cmd/ronin/chaincmd.go, cmd/ronin/main.go, cmd/utils/flags.go, core/blockchain.go, core/blockchain_test.go, eth/backend.go, eth/ethconfig/config.go
This commit adds a flag --no-pruning-sidecar (default: true) to disable blob sidecar pruning in archive node. Blob sidecar is meant to be pruned, but in the early state where the offchain storage is not available, it might be better to keep it in archive node for debugging.
=> core: don't prune blob sidecar in archive node

cmd/utils/flags.go, core/vm/consortium_precompiled_contracts.go, core/vm/contracts.go, core/vm/contracts_test.go
This precompiled contract is unused and may cause the node with environment variable DEBUG=true to halt. So we decide to remove this precompiled contract after Cancun and remove the logic when DEBUG=true, make this precompiled contract always return (input, nil).
Reported-by: Dontonka
=> core/vm: remove consortiumLog precompiled contract after Cancun

crypto/bn256/cloudflare/gfp12.go, crypto/bn256/google/gfp12.go
commit https://github.com/ethereum/go-ethereum/commit/0feb999d3fd190cc67c59fc91b7094e54ff8e1a2.
The `a` parameter should be used in the `MulScalar` function. The upstream cloudflare and google repos have already merged fixes.
Reference:
* https://cs.opensource.google/go/x/crypto/+/8d7daa0c54b357f3071e11eaef7efc4e19a417e2
* https://github.com/cloudflare/bn256/pull/33
Reported-by: Sujith Somraaj \<somraajsujith@gmail.com\>
=> crypto/bn256: fix MulScalar (#30974)

core/rawdb/freezer.go
commit https://github.com/ethereum/go-ethereum/commit/c5a8d3485191d15363b9817da1afcac3fce5ddeb.
Fixes an issue where the node panics when an LStat fails with something other than os.ErrNotExist
Reported-by: eugenioclrc \<eugenioclrc@gmail.com\>
=> core/rawdb: fix panic in freezer (#30973)

core/bloombits/matcher.go
commit https://github.com/ethereum/go-ethereum/commit/c2cfe35f121cb88650b4d90c958bcc4214d0ce7f.
When MatcherSession encounters an error, it attempts to close the session. Closing waits for all goroutines to finish, including the 'distributor'. However, the distributor will not exit until all requests have returned.
This patch fixes the issue by delivering the (empty) result to the distributor before calling Close().
Reported-by: eugenioclrc \<eugenioclrc@gmail.com\>
=> core/bloombits: fix deadlock when matcher session hits an error (#28184)

eth/tracers/api.go
The current transactionHash field in transaction trace response should be named txHash to be compatible with go-ethereum. This commit adds txHash instead of replacing the current transactionHash field and make them have the same value. This can help to avoid breaking change for current users of these methods since users are unlikely to use strict DisallowUnknownFields when decoding the json response.
Fixes: #647
=> eth/tracers: make transaction trace response compatible with geth

README.md
Update the Ronin whitepaper's link to:
https://docs.roninchain.com/basics/white-paper/
=> README: update Ronin whitepaper's link

accounts/abi/error.go
Adds contextual information to errors returned by unpack
Cherry-pick: https://github.com/ethereum/go-ethereum/pull/28529
=> accounts/abi: context info on unpack-errors (#28529)

accounts/abi/topics.go, accounts/abi/topics_test.go
- accounts/abi: fix bigInt topic encoding (#28764)
commit https://github.com/ethereum/go-ethereum/commit/d0edc5af4a2f4e8e9961c5da4d710579ff19681f.
Currectly encode the negative bigInt. Currently, bigInt(-1) is encoded as
0000000000...000000000001, while it should be ffffffffff...ffff instead.
- accounts/abi: fix MakeTopics mutation of big.Int inputs (#30785)
commit https://github.com/ethereum/go-ethereum/commit/3c754e2a09d112cd62f4d51f221637f9a147dcc6.
also changed the behavior of the function from just _reading_ the input
`*big.Int` via `Bytes()`, to leveraging `big.U256Bytes` which is documented as
being _destructive_:
This change updates `MakeTopics` to not mutate the original.
Reported-by: eugenioclrc \<eugenioclrc@gmail.com\>
=> accounts/abi: fix bigInt topic encoding

core/state_processor.go, core/txpool/validation.go, core/vm/evm.go
After Venoki, we don't have to check for whitelisted and blacklisted contract deployers anymore.
This help boost performance by not access to state for checking.
=> txpool, evm: skip blacklist and whitelist deployer check after Venoki
