axieinfinity/ronin

- core/blockchain.go
- core/blockchain_reader.go
- core/events.go
- core/state/statedb.go
- core/types/state_account.go
- eth/api_backend.go
- internal/ethapi/backend.go
- les/api_backend.go
- light/lightchain.go
- miner/worker.go
Add method `SubscribeDirtyAccountEvent` to publish dirty accounts
> feat: add dirty account feed

- consensus/consortium/v2/consortium.go
This commit makes all read of signer fields in consortium v2 hold read mutex lock to synchronize with read mutex lock in Consortium.Authorize function.
> fix: data race in signer fields in consortium v2

- eth/filters/filter.go
We add an environment variable to set the block range limit in log filter query.
> feat: add limit for block range in log filter

- miner/worker.go
- miner/worker_test.go
This ports BSC commit to Ronin:
https://github.com/bnb-chain/bsc/commit/d87d697d927c9dd0d24ee31e15b23e0f760469fa
Due to recommit logic, a non-malicious node can produce 2 blocks with the same block number and parent hash which violates the double signing rule. This commit drops the possibly violated block.
TODO:
> fix: avoid double signing block due to recommit

- consensus/consortium/v1/consortium.go
We expect only the last block in consortium v1 has a system transaction and that system transaction is wrapUpEpoch. This commit adds checks to ensure that expectation.
> fix: check the system transaction in consortium v1

- core/blockchain_reader.go
- core/vm/instructions.go
This PR supports publishing DELEGATECALL opcode event to `SubscribeInternalTransaction`.
> feat: publish DELEGATECALL opcode event

- consensus/consortium/common/contract.go
Correct the system transactions that passed into EVM for publishing internal transactions.
> fix: system transaction hash for publishing internal transactions

- cmd/ronin/main.go
- cmd/ronin/usage.go
- cmd/utils/flags.go
- eth/ethconfig/config.go
- genesis/mainnet.json
- miner/miner.go
- miner/worker.go
The Olek hardfork is forecasted to be at 12:00 UTC+7 ,Jun 13th (https://app.roninchain.com/block/24935500)
> config: add Olek hardfork on mainnet

- core/vm/evm.go
This PR introduces the `fullCallTracing` feature for the `create` and `deletagatecall` opcodes, while also addressing a bug in the `call` opcode.
Fix #290
> evm: add fullCallTracing create, delegatecall and fix call opcode

- core/types/vote.go
- core/vote/vote_manager.go
- core/vote/vote_pool_test.go
RawVoteEnvelop is the same as VoteEnvelop without cached hash
> core/types/vote: introduce RawVoteEnvelop

- consensus/consensus.go
- consensus/consortium/main.go
- consensus/consortium/v2/consortium.go
- core/blockchain.go
- monitor/finality_vote.go
- monitor/finality_vote_test.go
This monitor gets the information from block header and check if a voter votes
for 2 distinct block at the same height.
> monitor/finality_vote: add finality vote monitor

- consensus/consortium/v2/consortium_test.go
- consensus/consortium/v2/finality/consortium_header.go
The blsCommon.PublicKey cannot be un/marshalled to json, this commit converts that field to hex string before marshalling to json.
> consortium/v2: fix snapshot save after Shillin

- consensus/consortium/v2/consortium.go
- consensus/consortium/v2/consortium_test.go
The commit fixes the bug when collects and aggregates signatures from vote pool.
> consortium/v2: fix the finality vote fetch from pool

- Dockerfile
- docker/chainnode/entrypoint.sh
- entrypoint: fix bash script syntax
- Dockerfile: add required libstdc++ package
> Dockerfile, entrypoint: fix start script and install additional package

- Makefile
Reference: https://github.com/bnb-chain/bsc/pull/1403
> Makefile: fix devtools install error

- core/blockchain.go
- ethstats/ethstats.go
- monitor/slack_alerter.go
Reduce the log level of unimportant messages to make it easier to watch log.
> stats, blockchain, monitor: reduce and fixup the log message

- core/tx_pool.go
Update the transaction validation logic to use the whitelist deployer v2 after Antenna hardfork.
> tx_pool: update the transaction validation logic to whitelist deployer v2

- README.md
> fix bootnodes

- core/blockchain.go
- core/state_processor.go
- core/vm/evm.go
This commit adds hook to precompiled contract and create to fix the compatibility issues on testnet
> core/state: add hook to precompiled contract and create

- README.md
- cmd/clef/datatypes.md
> fix: typos

- core/blockchain_reader.go
nil check finalized block before getting its header in CurrentFinalBlock.
> core: add nil check when getting finalized block

- cmd/utils/cmd.go
- core/blockchain.go
- eth/api.go
Add support for block sidecars in import and export commands.
> cmd, api: support import and export block with sidecars

- params/config.go
Add the missing compatibility check for new Venoki fork block.
> params: add Venoki fork block compatibility check

- core/txpool/blobpool/blobpool.go
- core/txpool/blobpool/blobpool_test.go
- core/txpool/legacypool/legacypool.go
- core/txpool/legacypool/legacypool_test.go
- core/txpool/validation.go
effectiveTip = min(tipcap, feecap - basefee), so the too low feecap can make the effectiveTip not enough to cover the pool's required tip. This commit adds a check to ensure feecap is not lower the the pool's required tip + minimumBaseFee.
> txpool: ensure the max tip based on gas fee cap is high enough

- eth/downloader/queue.go
Part of commit https://github.com/ethereum/go-ethereum/commit/1f9b69b36d51988305de791d50d5422b5cc01ca6.
This commit add an early check for the number of delivered blob transactions with header's blob gas used when receiving block body packet.
> eth: early check the number of delivered blob transactions

- eth/sync.go
We need to check if the current head passes the required checkpoint and the
head is not too old before enabling accepting transactions. So disable
fast/snap sync and set pathdb's buffer manually, don't use enableSyncedFeatures
which enables accepting transaction unconditionally.
Reported-by: 0xarno \<0xarnosr@gmail.com\>
> eth: only enable accepting transactions after checking

- accounts/abi/bind/base_test.go
- accounts/abi/type.go
commit https://github.com/ethereum/go-ethereum/commit/af02e97929d47238fa0dbd233846270802b99e1a.
Reported-by: eugenioclrc \<eugenioclrc@gmail.com\>
> accounts/abi: validate fieldnames to avoid reflect.StructOf panic (#24932)

- core/rawdb/chain_freezer.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_test.go
- core/state/dump.go
- core/state/state_object.go
- core/state/statedb.go
- eth/api.go
- eth/api_test.go
- eth/handler.go
- internal/ethapi/api.go
- p2p/discover/table.go
- trie/trie.go
This PR including some fixes related to path base implementing and ENR filtering feature.
> core/rawdb, p2p/discover/table.go, trie, core/state, eth/handler: cherry pick bug fixes for path base implementing & enr filtering
